.circleci/config.yml

Codecov reporting

---

.eslintrc.js
package-lock.json
package.json
src/components/App.jsx
src/components/Search/SearchInput.jsx
src/components/Search/SearchResultsList.jsx
src/components/Search/SearchView.jsx
src/index.jsx
src/tests/App.test.jsx
src/tests/SearchView.test.jsx
src/tests/utils/test-utils.jsx

Add react router to perf compare

Add router to perf compare

---

src/tests/SearchView.test.jsx
src/tests/__snapshots__/SearchView.test.jsx.snap
src/utils/searchViewHelper.js

* added ability to search by short hash
* fixed regex to match exactly and only include a-f 0-9
* remove repeated assertions, change test strings to hashes

Add ability to search by short hash

---

src/components/Search/AddRevisionButton.tsx
src/components/Search/SearchInput.tsx
src/components/Search/SearchView.tsx
src/tests/App.test.tsx
src/tests/__snapshots__/SearchView.test.tsx.snap
src/theme/protocolTheme.js
src/theme/typography.js

added Add revision button, made results wider to view more information. 
Had to edit the App test to cover all lines, because we weren't rendering the actual component, it showed some lines uncovered

Add revision button

---

package-lock.json
package.json
src/common/store.ts
src/components/App.tsx
src/components/Search/SearchView/SearchView.css
src/components/Search/SearchView/SearchView.tsx
src/components/Search/SelectedRevisionsTable/SelectedRevisionsTable.css
src/components/Search/SelectedRevisionsTable/SelectedRevisionsTable.tsx
src/components/Shared/StyledTableCell.tsx
src/components/Shared/StyledTableRow.tsx
src/reducers/SelectedRevisions.tsx
src/tests/SearchView.test.tsx
src/tests/SelectedRevisionsTable.test.tsx
src/tests/__snapshots__/SearchView.test.tsx.snap
src/types/enums.ts
src/types/state.ts
src/types/tableHeaderDetails.ts
webpack.config.js

Add Perfcompare table, with mock data

add table with selected visions

---

.eslintrc.js
package-lock.json
package.json
src/components/Search/SearchResultsListItem.tsx
src/components/Search/SearchView/SearchView.tsx
src/reducers/SearchSlice.tsx
src/tests/utils/globalSetup.ts
src/tests/utils/test-utils.jsx
src/thunks/searchThunk.ts
src/types/api.ts
src/types/custom.d.ts
src/utils/searchViewHelper.ts

Typescript linting isn't correctly warning about types.

fix typescript linting

---

src/components/Search/SearchInput.tsx
src/components/Search/SearchView/SearchView.tsx
src/tests/__snapshots__/SearchView.test.tsx.snap

I realized that the margin on the right was smaller than on the left, so the input was not centered.

fix alignment to center input

---

src/components/Search/SearchView/SearchView.tsx
src/components/Search/SelectedRevisionsTable/SelectedRevisionsTable.tsx
src/tests/SelectedRevisionsTable.test.tsx

Add conditional rendering if there are no revisions

render nothing for perf compare selected revisions if there are no revisions

---

src/components/Search/SearchResultsList.tsx
src/components/Search/SearchResultsListItem.tsx
src/components/Search/SearchView.tsx
src/hooks/useCheckRevision.ts
src/tests/Search/SearchResultsList.test.tsx
src/tests/Search/__snapshots__/SearchView.test.tsx.snap
src/tests/Search/__snapshots__/fetchRecentRevisions.test.tsx.snap
src/tests/Search/__snapshots__/fetchRevisionByID.test.tsx.snap
src/tests/Search/__snapshots__/fetchRevisionsByAuthor.test.tsx.snap
src/tests/utils/fixtures.ts

Added hook to handle checked revisions, and output a message to console when a user tries to select more than four. Added TODO to replace console message with a modal notification.
This PR is based on #100 and #93 and will be blocked until those are merged.

Handle checked revisions

---

src/tests/Search/SearchResultsList.test.tsx

Missed an import in the linting PR. also remove the jsdom tag, fixed in #107

Remove unused import to fix linting

---

src/tests/Search/SearchView.test.tsx
src/tests/Search/fetchRevisionByID.test.tsx
src/tests/Search/fetchRevisionsByAuthor.test.tsx

Moved a test that was in SearchView.test to fetchRevisionByID and added similar test to fetchRevisionsByAuthor

moved fetch by id test and added similar test to fetch by author

---

package-lock.json
package.json

Using this library significantly improves test run time. fixes #134

use swc-jest in place of babel and ts-jest

---

src/types/enums.ts

This doesn't appear to be needed anymore

remove lint rule

---

src/components/Results/ResultsTable.tsx
src/components/Results/ResultsView.tsx
src/components/Shared/SelectedRevisionsTable.tsx
src/tests/Results/ResultsView.test.tsx
src/tests/Results/__snapshots__/ResultsView.test.tsx.snap
src/types/enums.ts

basic results table

---

src/common/store.ts
src/reducers/SearchSlice.ts
src/reducers/SelectedRevisions.ts
src/tests/App.test.tsx
src/tests/Results/ResultsView.test.tsx
src/tests/Search/SearchResultsList.test.tsx
src/tests/Search/SearchView.test.tsx
src/tests/Search/__snapshots__/SearchView.test.tsx.snap
src/tests/Search/fetchRecentRevisions.test.tsx
src/tests/Search/fetchRevisionByID.test.tsx
src/tests/Search/fetchRevisionsByAuthor.test.tsx
src/tests/SelectedRevisionsTable.test.tsx
src/tests/Snackbar.test.tsx
src/tests/__snapshots__/SelectedRevisionsTable.test.tsx.snap
src/tests/utils/setupTests.ts
src/tests/utils/test-utils.tsx

fixes #115
added function to create new store for each test.
because we are using a helper function to create a new render and wrap UI components with a provider, I also had to add functions to create a new render and renderWithRouter for each test.

Create new store for each test

---

src/components/Search/SearchView.tsx
src/hooks/useFocusInput.ts
src/tests/Search/SearchView.test.tsx

hide search results when escape is pressed

---

src/components/CompareResults/CompareResultsView.tsx
src/components/Search/SearchView.tsx
src/components/Shared/SelectedRevisionsTable.tsx
src/components/Shared/SelectedRevisionsTableRow.tsx
src/tests/SelectedRevisionsTable.test.tsx
src/tests/__snapshots__/SelectedRevisionsTable.test.tsx.snap
src/tests/accessiblity/accessibility.test.tsx
src/theme/components.js

Render minified UI and edit button on results view

make selected revisions table a reusable component

---

.circleci/config.yml
README.md

* update readme contributing guide
* update CI to run on master and staging nightly

update CI to run on master and staging nightly

---

package-lock.json

the heroku deploy failed due to lockfile being out of date: 
```
-----> Installing dependencies
Installing node modules
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's @swc/core@1.2.224 does not satisfy @swc/core@1.2.235
npm ERR! Invalid: lock file's @swc/core-android-arm-eabi@1.2.224 does not satisfy @swc/core-android-arm-eabi@1.2.235
npm ERR! Invalid: lock file's @swc/core-android-arm64@1.2.224 does not satisfy @swc/core-android-arm64@1.2.235
npm ERR! Invalid: lock file's @swc/core-darwin-arm64@1.2.224 does not satisfy @swc/core-darwin-arm64@1.2.235
npm ERR! Invalid: lock …
```

update lockfile to fix deployment 

---

webpack/webpack.development.js

Fortunately this turned out to be a very simple fix :)

fix 'cannot get route' on refresh

---

src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/__snapshots__/SelectedRevisionsTable.test.tsx.snap
src/components/Shared/RevisionSearch.tsx

[Ready for review] search results error breaks UI #243

---

src/__tests__/hooks/useHandleChangeSearch.test.ts
src/__tests__/utils/setupTests.ts
src/__tests__/utils/test-utils.tsx
src/hooks/useHandleChangeSearch.ts

[Ready for review] recent revisions only fetch on render #244

---

src/__tests__/Snackbar.test.tsx
src/__tests__/hooks/useFetchCompareResults.test.ts
src/__tests__/hooks/useFetchCompareResults.ts
src/__tests__/hooks/useQueryParams.test.ts
src/__tests__/utils/test-utils.tsx
src/components/Shared/FeedbackAlert.tsx

resolves #210
it should be considered for review after merging the https://github.com/mozilla/perfcompare/pull/284

[RFR] Increase hook test coverage

---

src/__tests__/Snackbar.test.tsx
src/components/Shared/FeedbackAlert.tsx

adding tests for `FeedbackAlert` component,
Removing `ClickAwayListener` wrapper

[Ready for review] adding FeedbackAlert tests

---

src/__tests__/Search/SearchViewBeta.test.tsx
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchViewBeta.test.tsx.snap
src/__tests__/__snapshots__/SelectedRevisionsTable.test.tsx.snap
src/components/App.tsx
src/components/CompareResults/CompareResultsTableHead.tsx
src/components/Search/SearchDropdown.tsx
src/components/Search/beta/SearchView.tsx
src/components/Shared/FeedbackAlert.tsx
src/components/Shared/ToggleDarkModeButton.tsx
src/components/Shared/beta/PerfCompareHeader.tsx
src/components/Shared/beta/ToggleDarkModeButton.tsx
src/resources/Strings.tsx
src/styles/Buttons.ts
src/styles/Fonts.ts
src/styles/Switch.ts
src/styles/index.tsx

This PR fulfills the Jira ticket: https://mozilla-hub.atlassian.net/browse/PCF-237:
**Note: coverage and dark mode functionality will be covered in separate tickets/PRs.**
- To view the new headger please import  `SearchView from './Search/beta/SearchView'` in `App.tsx`
- `Feedback Alert Box` and the original `ToggleDarkModeButton` are set to `display:none`.  
**- Note: I noticed that the feedback alert box isn't in the new design. Should we find a place to put it?**
- I've also left the warning label; I'm assumed we'd like to keep it.

header, button and switch styles

---

src/components/CompareResults/EditRevisionButton.tsx

Reverts mozilla/perfcompare#304

Revert "fix popover width so that it becomes equal to table width"

---

README.md
package-lock.json
package.json
src/__tests__/accessiblity/accessibility.test.tsx

Fixed act warnings appearing in the accessibility tests, and one test was missing the view prop
also added a test for compare view in dark mode.

fix errors in accessibility test #218

---

src/__tests__/CompareResults/beta/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/beta/__snapshots__/SearchInput.test.tsx.snap
src/components/CompareResults/beta/DownloadButton.tsx
src/components/CompareResults/beta/ResultsHeader.tsx
src/components/CompareResults/beta/SearchInput.tsx

This PR adds the Download JSON button in disabled mode.

PCF-225 Add disabled component for downloading the JSON data

---

src/__tests__/CompareResults/beta/RevisionSelect.test.tsx
src/__tests__/CompareResults/beta/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/beta/__snapshots__/RevisionSelect.test.tsx.snap
src/__tests__/CompareResults/beta/__snapshots__/SearchInput.test.tsx.snap
src/components/App.tsx
src/components/CompareResults/beta/ResultsHeader.tsx
src/components/CompareResults/beta/RevisionSelect.tsx
src/components/CompareResults/beta/SearchInput.tsx

Added the component for selecting a revision in disable mode.

PCF-224 Results: Display disabled component for all revisions dropdown

---

package-lock.json

hey,
I made these small updates to some dependencies. Webpack has a security advisories, and the caniuse update was suggested by browserslist when I ran the build locally.
As far as I know this still builds properly but please double check because I don't know much :-)

Update webpack and caniuse

---

.nvmrc

This is one of the methods to [automatically configure netlify](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript). I like it because this puts us in control (as we won't have access to the netlify control panel), so it's easy to update.
I only specified the major version. We may also want to add the constraint to package.json's `engines` property so that every developer is on the same major version. But that could be for later :-)
Tell me what you think!

Add a .nvmrc file so that netlify can use it to configure the node version

---

Deployment.md
README.md
bin/revert-last-deployment.sh

I wrote some documentation about how to deploy to production. I mostly copied/pasted from the profiler doc. I also copied the "revert to previous version" script from there, and of course adjusted it for this project too.
Tell me what you think!

Add some documentation about deployment

---

src/__tests__/CompareResults/beta/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/utils/fixtures.ts
src/components/CompareResults/beta/Distribution.tsx
src/components/CompareResults/beta/RevisionRowExpandable.tsx
src/components/CompareResults/beta/RunValues.tsx
src/mockData/9d5066525489.ts
src/mockData/a998c42399a8.ts
src/mockData/bb6a5e451dac.ts
src/types/state.ts

Display application for expanded row with one run:
Display application for expanded row with multiple runs:
For testing just use the [fakedata](https://deploy-preview-531--mozilla-perfcompare.netlify.app/#/compare-results/?fakedata=true).

Display the application name

---

src/components/Search/CompareWithBase.tsx
src/components/Shared/ToggleDarkModeButton.tsx

This changes or removes some effects (and states !) that weren't correct. In most of the cases we're now computing things while rendering directly.

Remove some useless effects

---

src/components/CompareResults/RevisionRow.tsx
src/components/Search/CompareWithBase.tsx

Addressing the comment from https://github.com/mozilla/perfcompare/pull/555/files#r1345768529

Compute class expanded where needed

---

src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/SearchView.test.tsx
src/components/CompareResults/ResultsView.tsx
src/components/Search/CompareWithBase.tsx
src/components/Search/SearchContainer.tsx

This flats out the objects we used to pass some of the props to CompareWithBase. Indeed I realized that we were using useMemo to change the objects shapes, and all that. Instead I found it was easier to pass individual props.
Tell me what you think :-)

Simplify how we pass the props to CompareWithBase

---

src/index.tsx

This change disables only this specific eslint rule on this specific line, while before this was disabling all of eslint on the rest of the file.

Make a eslint assertion more specific

---

public/index.html

Addresses [Bug 1874016](https://bugzilla.mozilla.org/show_bug.cgi?id=1874016)

Bug 1874016 - <meta name="description" content="Web site created using create-react-app"/>

---

src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SearchInput.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/TableHeader.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/fetchCompareResults.test.tsx.snap
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/TableContent.tsx
src/components/CompareResults/TableHeader.tsx

This is a follow-up PR to address https://github.com/mozilla/perfcompare/pull/580#pullrequestreview-1770187205

PCF-361 Add aria roles for tables / rows / rowgroup etc

---

src/components/App.tsx

It fulfills [Define the login route for taskcluster auth](https://mozilla-hub.atlassian.net/browse/PCF-398).

PCF-53 Define the login route for taskcluster auth

---

src/__tests__/Search/SearchView.test.tsx
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/resources/Strings.tsx

Sorry about this but I rebased my last PR (#644 ) incorrectly so I have to push this again. :-/

Revert comparebutton name change

---

src/__tests__/Search/CompareOverTime.test.tsx
src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/components/Search/CompareWithBase.tsx
src/resources/Strings.tsx

My last patch had a bug for the base component title. I also added two tests to make sure the titles are always correct.

base title fix with new tests

---

src/__tests__/App.test.tsx
src/__tests__/CompareResults/OverTimeResultsView.test.tsx
src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/Search/CompareOverTime.test.tsx
src/__tests__/Search/SearchView.test.tsx
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/__snapshots__/App.test.tsx.snap
src/components/App.tsx
src/components/CompareResults/OverTimeResultsView.tsx
src/components/Search/CompareOverTime.tsx
src/resources/Strings.tsx

-`OverTimeResultsView` test
-handled no revisions selected error case for compare over time `Compare` button 
-handled redirect to compare-over-time-results page

added new tests

---

src/__tests__/App.test.tsx
src/__tests__/Search/CompareOverTime.test.tsx
src/__tests__/Search/SearchView.test.tsx
src/__tests__/__snapshots__/App.test.tsx.snap
src/components/CompareResults/overTimeLoader.ts

Also fixed a bug re getting interval info from url while writing tests for overTimeLoader.

added coverage for overTimeLoader

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
src/components/CompareResults/ResultsMain.tsx
src/components/CompareResults/ResultsTable.tsx
src/theme/components.js

This removes some unused style as well as some clashing styles.

Fix the bad layout happening sometimes in the compare results

---

src/__tests__/utils/fixtures.ts
src/components/App.tsx
src/components/CompareResults/SubtestsResultsView.tsx
src/components/CompareResults/subtestsLoader.ts
src/components/CompareResults/subtestsOverTimeLoader.tsx
src/logic/treeherder.ts
src/mockData/9d50665254899d8431813bdc04178e6006ce6d59.ts
src/mockData/a998c42399a8fcea623690bf65bef49de20535b4.ts
src/mockData/bb6a5e451dace3b9c7be42d24c9272738d73e6db.ts
src/types/state.ts

Testing links:
[Subtests from comparison with base rev](https://deploy-preview-655--mozilla-perfcompare.netlify.app/subtestsCompareWithBase?baseRev=42f8b13731a592d1a25e662692cbd82cee5012e0&baseRepo=mozilla-central&newRev=80ae2c7908e4cc558336a6f6a78097d9c2c9317d&newRepo=mozilla-central&framework=1&parentSignature=4769486)
[Subtests from comparison over time ](https://deploy-preview-655--mozilla-perfcompare.netlify.app/subtestsCompareOverTime?baseRepo=mozilla-central&newRev=d5738a6a3f878a3a8eb8c4c5d7e544d11b6b344a&newRepo=mozilla-central&framework=1&parentSignature=4769486&interval=172800)
(Julien's note: I replaced localhost with the deploy preview domain in your links)

React router loader for subtests view

---

src/logic/taskcluster.ts

[Jira ticket PCF-463](https://mozilla-hub.atlassian.net/browse/PCF-463)
If retrigger times is 0, the trigger request will not happen.

PCF-463 Do not run a retrigger request if the user picked "0" as the number of times

---

src/logic/taskcluster.ts

Just added a condition for checking the expiration date. 
Addresses [Jira ticket PCF-462](https://mozilla-hub.atlassian.net/browse/PCF-462).

PCF-462 Request credentials if the current stored ones are expired

---

src/__tests__/Search/CompareOverTime.test.tsx
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/components/Search/CompareOverTime.tsx

Compare Over Time: remove reload attribute from the form and update over time tests

---

src/__tests__/Search/CompareOverTime.test.tsx
src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/components/Search/CompareOverTime.tsx
src/components/Search/CompareWithBase.tsx

This quick PR hides the forms and buttons (exit edit mode) once the user clicks Compare in the Results Page.

Results Page: Exit edit mode post updates

---

src/__tests__/Search/CompareOverTime.test.tsx
src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/components/Search/CompareOverTime.tsx
src/components/Search/CompareWithBase.tsx

[Carla Severe] Compare Over Time: remove reload attribute from the form and update over time tests (#716)
[Carla Severe] Results Page: Exit edit mode post updates (#715)

Deploy August 10, 2024

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/RevisionRow.tsx
src/resources/Strings.tsx

[beatrice-acasandrei] Remove the download profiles icon (#718)
[Nazım Can Altınova] Make the improvement/regressions eaier to find by adding some colors and icons (#720)

Deploy Aug 16, 2024

---

src/__tests__/CompareResults/Retrigger.test.tsx
src/components/CompareResults/Retrigger/RetriggerButton.tsx
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsMain.tsx

[Jira ticket](https://mozilla-hub.atlassian.net/browse/PCF-484)
https://deploy-preview-711--mozilla-perfcompare.netlify.app/subtestsCompareWithBase?baseRev=7742b23a126df264dec9eff7c299afe33c6ca74f&baseRepo=mozilla-central&newRev=2e86cbfb869e1b6abc6ee9cee177f4f7484b7cb2&newRepo=mozilla-central&framework=1&baseParentSignature=4769486&newParentSignature=4769486

PCF-484 Add the retrigger test functionality for subtests

---

src/__tests__/CompareResults/Retrigger.test.tsx
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/components/App.tsx
src/components/CompareResults/OverTimeResultsView.tsx
src/components/CompareResults/ResultsView.tsx
src/components/CompareResults/Retrigger/RetriggerButton.tsx
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsBreadcrumbs.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsMain.tsx
src/components/CompareResults/subtestsOverTimeLoader.tsx
src/components/Search/CompareOverTime.tsx
src/components/Search/CompareWithBase.tsx
src/components/Search/SearchContainer.tsx

[esanuandra] PCF-484 Add the retrigger test functionality for subtests (#711)
[Julien Wajsberg] Simplify the state changing of the block expansions in the home page (#727)
[beatrice-acasandrei] Update subtests route and modify search param to selectedTimeRange (#731)
[esanuandra] Transition subtest header to grid layout (#732)

Deploy Aug 26, 2024

---

src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/RevisionRowExpandable.tsx

This PR displays the graph even when we have only one run.
[Jira ticket](https://mozilla-hub.atlassian.net/browse/PCF-506)

PCF-506 Always show the graphs

---

src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/RevisionRowExpandable.tsx
src/components/CompareResults/RunValues.tsx

Added measurement unit for standard deviation and mean difference.

PCF-504 Use units where needed in the expanded row

---

Deployment.md
README.md
src/logic/taskcluster.ts

I also added some tips to gather changes when deploying.

Update existing references to the beta branch

---

src/__tests__/App.test.tsx
src/__tests__/Search/SearchResultsList.test.tsx
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/components/Search/SearchResultsList.tsx
src/styles/SelectList.ts

Moved specific results list styles to `SearchResultsList` because they were only used once in `styles/SelectList`
Fix for issue[ PCF-502](https://mozilla-hub.atlassian.net/browse/PCF-502). Let me know if the height is satisfactory or if I should increase even more.

PCF-502: increased height of results list to show first five items

---

README.md
package-lock.json
package.json
src/__tests__/App.test.tsx
src/__tests__/CompareResults/RevisionSelect.test.tsx
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/Search/CompareOverTime.test.tsx
src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/SearchResultsList.test.tsx
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/TaskclusterAuth/TaskclusterCallback.test.tsx
src/__tests__/TaskclusterAuth/__snapshots__/TaskclusterCallback.test.tsx.snap
src/components/CompareResults/ResultsMain.tsx
src/components/CompareResults/Retrigger/RetriggerConfigModal.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsMain.tsx
src/components/Search/CompareOverTime.tsx
src/components/Search/CompareWithBase.tsx
src/components/Search/SearchContainer.tsx
src/components/Search/SearchFormHeader.tsx
src/components/Search/SearchResultsList.tsx
src/components/TaskclusterAuth/TaskclusterCallback.tsx
src/components/TaskclusterAuth/loader.ts
src/logic/taskcluster.ts
src/logic/treeherder.ts
src/resources/Strings.tsx
src/styles/SelectList.ts
src/types/state.ts

[Carla Severe] PCF-502: increased height of results list to show first five items (#758)
[Julien Wajsberg] Increase the maximum amount of possible retriggers to 9 (#760)
[beatrice-acasandrei] Add links to the perfcompare app linking to the old compareview, keeping the same revisions (#728)
[esanuandra] PCF-426 Improve the "Results" title to be more visible and contain the context (eg: "Compare with base") (#752)
[esanuandra] PCF-427 Redesign the search form to make it more compact (#759)
[Julien Wajsberg] Redesign the landing page after the taskcluster signin to show feedback to the user (#761)

Deploy Oct 9, 2024

---

src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/components/Search/CancelAndCompareButtons.tsx
src/components/Search/CompareOverTime.tsx
src/components/Search/CompareWithBase.tsx
src/styles/CompareCards.ts

Follow up PR for https://github.com/mozilla/perfcompare/pull/759

Reduce margins for search form

---

src/__tests__/Search/SearchView.test.tsx
src/__tests__/Search/fetchRevisionsByAuthor.test.tsx
src/components/Search/SearchInputAndResults.tsx
src/logic/treeherder.ts
src/resources/Strings.tsx

[Jira ticket](https://mozilla-hub.atlassian.net/browse/PCF-501)

PCF-501 Search by email should  be using substrings

---

src/__tests__/CompareResults/ResultsTable.test.tsx
src/__tests__/CompareResults/RevisionRow.test.tsx
src/__tests__/utils/platform.test.ts
src/components/CompareResults/RevisionRow.tsx
src/utils/platform.ts

[Jira ticket](https://mozilla-hub.atlassian.net/browse/PCF-549)
[localhost test link](http://localhost:3000/compare-results?baseRev=b6fe6098a8bbf74edca23103c6756be13d238378&baseRepo=mozilla-central&newRev=b136e0dc43e39a2da4f7d375ef545d230caa86c0&newRepo=mozilla-central&newRev=9358b6a02a04f62e0c9c7fcba4877700076a28f5&newRepo=mozilla-central&framework=13&search=speedometer)
[deploy preview test link](https://deploy-preview-803--mozilla-perfcompare.netlify.app/compare-results?baseRev=b6fe6098a8bbf74edca23103c6756be13d238378&baseRepo=mozilla-central&newRev=b136e0dc43e39a2da4f7d375ef545d230caa86c0&newRepo=mozilla-central&newRev=9358b6a02a04f62e0c9c7fcba4877700076a28f5&newRepo=mozilla-central&framework=13&search=speedometer)
Adding android device name next to platform name.

PCF-549 Add the name of the device used instead of just "Android"

---

README.md

Quick PR to update the documentation link.

Update perfcompare doc link in ReadME

---

src/components/CompareResults/TableHeader.tsx

[Jira ticket](https://mozilla-hub.atlassian.net/browse/PCF-576)
Before:
After:
[deploy](https://deploy-preview-818--mozilla-perfcompare.netlify.app/compare-results?baseRev=e3b3fa7a28a0e217ef910e1ec71d903eb01c7970&baseRepo=mozilla-central&newRev=70cf5d90c346d5954f08633c22f5eb6b6cd90d66&newRepo=mozilla-central&framework=1) vs [production](https://perf.compare/compare-results?baseRev=e3b3fa7a28a0e217ef910e1ec71d903eb01c7970&baseRepo=mozilla-central&newRev=70cf5d90c346d5954f08633c22f5eb6b6cd90d66&newRepo=mozilla-central&framework=1)

PCF-576 Add checkboxes to the table filters dropdown

---

src/components/CompareResults/SubtestsResults/SubtestsResultsTable.tsx
src/components/CompareResults/TableContent.tsx
src/hooks/useTableFilters.ts

This reduces duplication. When I first implemented this, I wasn't sure how much the 2 implementations (in main results page / in subtests results page) would be similar, but it turns our they are pretty similar after all.
I decided to move the code to filter the results to the hook file so that it's close to the code that handles the state. I believe it makes a consistent code unit this way, rather than creating a separate file.
There should be no user-visible change.
[deploy preview for the main page](https://deploy-preview-839--mozilla-perfcompare.netlify.app/compare-results?baseRev=d140333670bcd3103a668a5ec04ed438bb192368&baseRepo=mozilla-central&newRev=250be4ca3c669db9a397456402f68249aa15d8d5&newRepo=mozilla-central&framework=13&sort=delta%7Cdesc)
[deploy preview for the subtests …

Extract the table filtering code to a common file

---

src/__tests__/CompareResults/SearchInput.test.tsx
src/components/CompareResults/TableContent.tsx

Fix React error that the number of hooks is different between renders

---

.circleci/config.yml
README.md
package-lock.json
package.json
src/__tests__/CompareResults/SearchInput.test.tsx
src/components/CompareResults/TableContent.tsx

[Julien Wajsberg] Fix React error that the number of hooks is different between renders (#845)

Deploy Jan 24, 2025

---

src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/RevisionRowExpandable.tsx
src/resources/Strings.tsx

PCF-458 The note information about the Confidence value isn't useful enough

---

src/__tests__/CompareResults/RevisionRow.test.tsx
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/utils/fixtures.ts
src/components/CompareResults/RunValues.tsx

Jira: PCF-561
[localhost test link results page](http://localhost:3000/compare-over-time-results?baseRepo=try&selectedTimeRange=1209600&newRev=301fd7df21a146720ac180a15dbfd007b090dcaf&newRepo=try&framework=1)
[localhost test link subtests page](http://localhost:3000/subtests-compare-over-time-results?baseRepo=try&newRev=301fd7df21a146720ac180a15dbfd007b090dcaf&newRepo=try&framework=1&selectedTimeRange=1209600&baseParentSignature=4764992&newParentSignature=4764992)
[deploy test link](https://deploy-preview-844--mozilla-perfcompare.netlify.app/compare-over-time-results?baseRepo=try&selectedTimeRange=1209600&newRev=301fd7df21a146720ac180a15dbfd007b090dcaf&newRepo=try&framework=1)

PCF-561 When there are a lot of replicates, the expanded row with all the runs is too long

---

.circleci/config.yml
.nvmrc
README.md
package-lock.json
package.json
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap

I'm updating all the projects I work on to use node v22 instead of 18 or 20.
In this project this mostly means that some test snapshots had to be regenerated, because the output of some locale-dependent strings changed with the node update.
But otherwise everything seems to work fine. Locally I tried:
* the development server
* building the app
I also checked the netlify deploy preview because this is the closest of our production environment.

Update the project to node v22

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsRevisionRow.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
src/__tests__/__snapshots__/App.test.tsx.snap
src/components/CompareResults/LinkToRevision.tsx
src/components/CompareResults/ResultsMain.tsx
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsMain.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsTable.tsx
src/components/CompareResults/SubtestsResults/SubtestsRevisionHeader.tsx
src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx
src/components/CompareResults/TableHeader.tsx
src/components/CompareResults/TestHeader.tsx
src/styles/Fonts.ts
src/styles/SelectList.ts
src/styles/SelectedRevsStyle.ts
src/styles/Tooltips.ts
src/theme/components.js

**Increased** the `font size` for revision rows from `13px` to `16px` for better readability. Open to discussion on other elements that might benefit from a font size increase—feedback is welcome!

Increase fontSize from `13px` to `16px` 

---

src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
src/components/Search/CompareOverTime.tsx
src/components/Search/CompareWithBase.tsx

[Jira ticket](https://mozilla-hub.atlassian.net/browse/PCF-580)

PCF-580 Disable autocomplete on the search form

---

package-lock.json
src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/Retrigger.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
src/__tests__/Search/fetchRevisionFromHash.test.tsx
src/__tests__/__snapshots__/App.test.tsx.snap
src/components/CompareResults/loader.ts
src/components/Search/CompareOverTime.tsx
src/components/Search/CompareWithBase.tsx
src/components/Search/SearchComponent.tsx
src/components/Search/SearchOverTime.tsx
src/components/Search/SelectedRevisionItem.tsx
src/logic/treeherder.ts
src/styles/CompareCards.ts
src/styles/Fonts.ts
src/styles/SearchContainerStyles.ts
src/styles/SelectedRevsStyle.ts
src/theme/components.js
src/types/state.ts

Here are the new changes:
[Carla Severe] Fix font UI bugs  (#873)
[esanuandra] PCF-580 Disable autocomplete on the search form (#874)
[Andrej Glavic] Bug 1949264 - Add git migration compatibility for ./mach try perf (#872)

Deploy April 29, 2025

---

src/__tests__/CompareResults/SubtestsRevisionRow.test.tsx
src/__tests__/CompareResults/__snapshots__/SubtestsRevisionRow.test.tsx.snap

This also fixes a warning about a missing `act`.

In the tests for SubtestsRevisionRow, wait until the page is rendered before asserting

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/LinkToRevision.tsx
src/components/CompareResults/TestHeader.tsx

[Jira ticket](https://mozilla-hub.atlassian.net/browse/PCF-523)
[Deploy test link](https://deploy-preview-877--mozilla-perfcompare.netlify.app/compare-results?baseRev=232849eaaf94591746a518bcfbb1973d544022e0&baseRepo=mozilla-central&newRev=8cfe77187cb705982852f38bb1b918a2f916aa28&newRepo=mozilla-central&framework=1) there are some examples down on the page with longer test names. I grouped the revision with the copy revision button so that the button does not go alone on the next row.

PCF-523 Results table: add nowrap to tags list

---

src/components/CompareResults/CommonGraph.tsx

Please look at the last commit only.
This PR improves the bandwidth computation. In the future we'll probably want to compute it on the server side using the algorithms already available in scipy, but that should improve it for now.
I used ChatGPT to help me with defining the algorithm.
[Before this patch](https://deploy-preview-902--mozilla-perfcompare.netlify.app/subtests-compare-results?baseRev=c5a8a6790e0f809403d4e2559f9d906984ea56f7&baseRepo=mozilla-central&newRev=5fb84cb353d47eb6342b68c4fd91dab68333be02&newRepo=mozilla-central&framework=13&baseParentSignature=5034830&newParentSignature=5034830)
[With this patch](https://deploy-preview-903--mozilla-perfcompare.netlify.app/subtests-compare-results?baseRev=c5a8a6790e0f809403d4e2559f9d906984ea56f7&baseRepo=mozilla-central&newRev=5fb84cb3 …

Change how the bandwidth is computed
