.eslintrc.js
src/reducers/SearchSlice.jsx
src/tests/SearchView.test.jsx
src/tests/searchThunk.test.js
src/tests/searchViewHelpers.test.js
src/tests/setupTests.js
src/thunks/searchThunk.js

the api call to fetch recent revisions or search results is called whenever a value is entered that matches a search hash or email. 
so, if typing "ksereduck@mozilla.com", the api call will be made at `ksereduck@mozilla.c` `ksereduck@mozilla.co`, and `ksereduck@mozilla.com`
I found that the results for the complete email would appear, then disappear, because one of the previous API calls completed after the valid one, and would overwrite the search results with an empty array

reject thunks that return no results

---

package-lock.json
package.json

Working on fixing deploy to heroku. The issue is that heroku calls `npm start`, which currently runs `react-scripts`. We have moved this to devDependencies to resolve audit issues, and heroku installs only production dependencies.
Added a script 'start-dev' to run the local build, and modified `start` to deploy using `serve`

fix heroku deployment

---

src/components/Search/SearchView.tsx
src/tests/Search/__snapshots__/SearchView.test.tsx.snap
src/tests/Search/__snapshots__/fetchRecentRevisions.test.tsx.snap
src/tests/Search/__snapshots__/fetchRevisionByID.test.tsx.snap
src/tests/Search/__snapshots__/fetchRevisionsByAuthor.test.tsx.snap
src/theme/components.js

I was sure I had styled the components properly to overlap the search results over the selected revisions and avoid pushing it down, but after merging I realized it was not properly styled, perhaps I made an error while rebasing, I'm not sure.
I could revert my previous PR, or move the table back above the input. I know it was my suggestion to move it below to begin with, but I didn't realize it would be so much work to overlay the results.
Another issue with properly overlapping is that it requires setting `position: absolute`, and this makes it difficult to keep the table centered and the desired width.

move selected revisions table to fix overlap

---

src/tests/utils/globalSetup.ts

Setting the `LC_ALL` variable to the value `C` ensures that all developers will use the same base locale.

Set the locale for tests to run the same accross the world

---

src/common/store.ts
src/components/Shared/HeaderAlert.tsx
src/components/Shared/PerfCompareHeader.tsx
src/hooks/useAlert.ts
src/hooks/useCheckRevision.ts
src/reducers/AlertSlice.tsx
src/tests/PerfCompareHeader.test.tsx
src/tests/Search/SearchResultsList.test.tsx
src/tests/Search/__snapshots__/SearchView.test.tsx.snap
src/tests/Search/__snapshots__/fetchRecentRevisions.test.tsx.snap
src/tests/Search/__snapshots__/fetchRevisionByID.test.tsx.snap
src/tests/Search/__snapshots__/fetchRevisionsByAuthor.test.tsx.snap
src/tests/__snapshots__/PerfCompareHeader.test.tsx.snap
src/types/state.ts

Added dismissable alert to Header component. This replaces the `console.log` statement when a user tries to select more than 4 revisions. Currently, because of the way the focus hook works, dismissing the notification will also hide the search results. I'd like to replace this with a timeout, or at least not hide the results somehow

create reusable modal alert

---

src/components/Search/SearchView.tsx
src/tests/Search/SearchResultsList.test.tsx
src/tests/Search/SearchView.test.tsx
src/tests/Search/__snapshots__/SearchView.test.tsx.snap
src/tests/Search/__snapshots__/fetchRecentRevisions.test.tsx.snap
src/tests/Search/__snapshots__/fetchRevisionByID.test.tsx.snap
src/tests/Search/__snapshots__/fetchRevisionsByAuthor.test.tsx.snap
src/tests/Search/fetchRecentRevisions.test.tsx
src/tests/Search/fetchRevisionByID.test.tsx
src/tests/Search/fetchRevisionsByAuthor.test.tsx
src/tests/SelectedRevisionsTable.test.tsx
src/tests/utils/test-utils.tsx
src/theme/components.js

remove absolute
Need to discuss with team first before moving the button above the search input field

add button to redirect to results page

---

package.json

`npm run test:coverage` was failing due to `export * from '@testing-library/react';` in `test-utils.tsx` not being covered by tests. added ignore paths to exclude tests from coverage

ignore tests in coverage

---

src/tests/Search/SearchView.test.tsx

it appears that the changes to the linter have resolved this and the override is no longer needed

remove lint rule override

---

src/components/Search/SearchView.tsx
src/tests/Search/SearchView.test.tsx

Sample url query params currently generated.
Need to confirm with kim how to generate the short code version of revisions
http://localhost:3000/compare-results?revs=0396329b7d2e5e15a0841736625cc89ceadb4cf4,451c34fdf54bf79c705e058531314baaac7e49e7,dc608e935c5901a6404e9c58a5f73084b396f318,9ab74fb00e731757852c19495351b9f15357c5d4&repos=4,4,4,4
after truncating the url looks more like this:
http://localhost:3000/compare-results?revs=65e579f52525,229fa0fcb904,401c2d7e80fb,c4f1589aaaf5&repos=1,1,1,1

Add parameters to url routing

---

src/components/Shared/RevisionSearch.tsx

when clicking the add revision button, sometimes the checked revisions would be cleared before the add revision action was dispatch. this was an error in the focus handling logic, so I added an if condition to do nothing if the target of a mouse click is `#add-revision-button` or a child of it.

fix input focus

---

.github/workflows/heroku-deploy.yml

This github action will automatically deploy to heroku on every push to `staging` and `master`
in the heroku pipeline, the staging app is named `perfcompare-staging`, and production app is named `perfcompare-master`.
this action will run on every push to `staging` and `master`, to the appropriate heroku app--`perfcompare-${GITHUB_REF_NAME}`.
`staging` deploys to `perfcompare-staging` and `master` deploys to `perfcompare-master`
This is a successful test run: https://github.com/kimberlythegeek/perfcompare/runs/7259859820
The name of the branch was `demo-deploy` and successfully deployed to a test app named `perfcompare-demo-deploy`: https://perfcompare-demo-deploy.herokuapp.com/

heroku deploy config

---

src/components/CompareResults/CompareResultsTable.tsx
src/components/CompareResults/CompareResultsView.tsx
src/components/CompareResults/EditSearchResultsTable.tsx
src/components/Search/SearchDropdown.tsx
src/components/Search/SearchInput.tsx
src/components/Search/SearchResultsListItem.tsx
src/components/Search/SearchView.tsx
src/components/Search/SearchViewInit.tsx
src/components/Shared/RevisionSearch.tsx
src/components/Shared/SelectedRevisionsTable.tsx
src/hooks/useCheckRevision.ts
src/hooks/useHandleChangeSearch.ts
src/hooks/useSelectRevision.ts
src/types/state.ts

in #198 I added typed hooks for useDispatch and useSelector, so I have replaced usage of useSelector with the typed hook useAppSelector
Also removed `State` type and replaced with `RootState`

replace usage of useSelector with typed hook useAppSelector

---

README.md
package-lock.json
package.json
server.js

After moving to webpack in #198, the heroku deployment is no longer working, as it is trying to run webpack, which is a dev dependency.
added express to serve the production app. Heroku uses `npm start` by default to run node apps, so I've added the script `npm run dev` to start the dev server.
demo app to show that this fixed the problem: https://perfcompare-webpack.herokuapp.com/

add express for heroku deploy

---

src/__tests__/Search/SearchResultsList.test.tsx
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/components/Search/SearchResultsListItem.tsx
src/hooks/useCheckRevision.ts
src/hooks/useSelectRevision.ts
src/reducers/CheckedRevisions.ts
src/types/state.ts

I ran in to an implementation problem while working on editing a revision from results view. since we are replacing a revision instaed of just adding a new one, we need a reference to the revision we are replacing.
previously the checkedRevisions state held a revisions index from searchResults. I've updated the state to hold the actual revision, which should resolve this problem.

store revision instead of index in checkedRevisions

---

src/__tests__/accessiblity/accessibility.test.tsx

there were `act` warnings appearing in the accessibility tests, and one test was missing the `view` prop
also added a test for compare view in dark mode

fix errors in accessibility test

---

src/__tests__/CompareResults/__snapshots__/CompareResultsView.test.tsx.snap

When resolving merge conflicts for merging `staging` to `master`, apparently I made an error that caused the snapshot test to fail.

fix snapshot test after resolving merge conflict

---

src/theme/components.js

Changed backgroundSize from "25%" to "290px". 
Does not change image size on screen resizing.

 #257 PerfCompare header underline resizes based on window size

---

src/__tests__/CompareResults/CompareResultsTable.test.tsx

This fix is needed to address the failing test when the popper is being closed.

Fix close filter popper test

---

src/components/CompareResults/EditRevisionButton.tsx

- I am a outreachy participant !
- Used  Paperprops to style the popover !
Resolves - #225

fix popover width so that it becomes equal to table width

---

README.md
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/components/Search/SearchResultsListItem.tsx

Some accessibility standards violations in the `SearchResultsList` component cause [tests](https://app.circleci.com/pipelines/github/mozilla/perfcompare/1103/workflows/8aaaeeb7-a7d5-422a-90fa-29257fe7c1e4/jobs/1107/parallel-runs/0/steps/0-107) to fail. These violations include:
1. Missing aria-label in certain `input`(checkbox) elements,
2. `li` element not being a direct descendant of `ul`, having other elements in-between,
3. and an interactive element(checkbox) nested within another interactive element(button).
1. The content of the unlabeled checkboxes (rendered by [`Checkbox`](https://mui.com/material-ui/react-checkbox/) in `SearchResultsListItem` component) were unidentifiable to assistive technologies like screen readers and users who rely on them.
2. The structure of the list of …

Resolved accessibility issues in `SearchResultsListItem` component

---

src/__tests__/CompareResults/__snapshots__/CompareResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/CompareResultsView.test.tsx.snap
src/components/CompareResults/CompareResultsTable.tsx

@Carla-Moz @kimberlythegeek 
I have specified widths for the columns so that the widths stay consistent and the layout remains responsive.
These changes are to ensure that the width of the columns stays consistent and does not change depending on the data contained within the columns.
This includes adding the MUI colgroup in CompareResultsTable.tsx component and specifying column widths in percentages.
**Before Changes**             |  **After Changes**
:-------------------------:|:-------------------------:
#267

Fix- Columns in results view are not a consistent width #267

---

src/__tests__/CompareResults/beta/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/beta/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/beta/__snapshots__/SearchInput.test.tsx.snap
src/__tests__/CompareResults/beta/__snapshots__/TableHeader.test.tsx.snap
src/components/CompareResults/beta/ResultsMain.tsx
src/components/CompareResults/beta/ResultsTable.tsx
src/components/CompareResults/beta/RevisionHeader.tsx
src/components/CompareResults/beta/RevisionRow.tsx
src/components/CompareResults/beta/TableContent.tsx
src/components/CompareResults/beta/TableHeader.tsx
src/styles/Document.ts

This can be tested on route /#/beta/compare-results
This PR fulfills  [PCF-227 Results: Display single table component for revision test result](https://mozilla-hub.atlassian.net/browse/PCF-227)

PCF-227 Results: Display single table component for revision test result

---

src/__tests__/Search/SearchViewBeta.test.tsx
src/__tests__/Search/__snapshots__/SearchViewBeta.test.tsx.snap
src/components/Search/beta/SearchDropdown.tsx

- Searchview renders correctly when there are no results.
- Search container renders "compare with base".
- Base Search renders repository dropdown in closed condition.
- Base Search should hide search results when clicking outside of search input.
- Base Search should hide the search results when Escape key is pressed.
- Base Search should not call fetch if search value is not a hash or email.
- Base search should clear search results if the search value is cleared.
- Base search should not hide search results when clicking search results.
- Base search should update error state with generic message if fetch error is undefined.
- Base search should disable adding more than one revision for the base search.
**Note:** Similar tests were previously used for the search view component, they …

Update tests for the new SearchView component

---

jest.config.ts
src/mockData/mockedFonts/Metropolis-Bold.woff2
src/styles/Fonts.ts
src/types/custom.d.ts

**Problem**
The location of the local fonts when referenced from the typestyle's method `fontFace` did not work well with the webpack configuration.
**Fix**
Multiple fixes were tried but the best possible solution was found on the **typestyle** github repository in a closed [issue](https://github.com/typestyle/typestyle/issues). 
```
// Imports just the URL
import metropolisFontURL from '../../public/fonts/Metropolis-Bold.woff2';
import sfFontURL from '../../public/fonts/sf-pro-text-regular.woff';
```

Fix: Fonts not loading on deployment

---

src/components/CompareResults/beta/NoResultsFound.tsx
src/resources/Strings.tsx

Add no results found message

---

.eslintrc.js
src/__tests__/Snackbar.test.tsx
src/components/App.tsx

Is part of solution for #486 issue.
It is very important for a user with visual impairment to know how the interface is reacting to their requests in real-time. It requires us to make sure that alerts are announced to someone using assistive technologies such as a screen reader. For this reason, we use the `aria-live` attribute. 
Aria-live attribute exposes the alert message in the accessibility tree so the screen reader can announce the message in real-time as the alert goes off.
Faced with the issue that custom attributes cannot be added to notistack alert itself. The `domRoot` attribute made available by notistack  in `<snackbarProvider>` is passed with an alert container that contains the alert and holds the `aria-live` attribute.
A component is used for this container. This component …

Implement aria-live attribute for notistack alerts

---

.babelrc
tsconfig.json

tsconfig was targeting an old version of javascript, which could trigger typescript error when using newer features of javascript.
I checked on https://kangax.github.io/compat-table/es2016plus/, and it looks like all browsers support es2022 just fine, except one minor thing in RegExp that we don't use.
I also removed an outdated configuration in babel.
I checked that all scripts were still working correctly and that the project would build. Please double check and with your IDE too, to see if everything looks right on your end too!

Update version of typescript target and slightly update babel config

---

src/components/CompareResults/beta/RevisionSelect.tsx

This PR fulfills [Results: Add implementation for switching between comparisons](https://mozilla-hub.atlassian.net/browse/PCF-250)
subtask: [Populate all revisions dropdown with real data](https://mozilla-hub.atlassian.net/browse/PCF-282)
STR:
1. Go to http://localhost:3000/ or https://deploy-preview-516--mozilla-perfcompare.netlify.app/
2. Select some base and new revisions for comparison
3. Click `Compare` to be redirected to results page
4. Click on `All revisions` dropdown
5. The revisions that were selected on the home page should be in this dropdown

PCF - 250 Results: Add implementation for switching between comparisons Part 2

---

src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/SearchView.test.tsx
src/__tests__/hooks/useFetchCompareResults.test.ts
src/__tests__/hooks/useFetchCompareResults.ts
src/components/CompareResults/beta/ResultsTable.tsx
src/components/CompareResults/beta/ResultsView.tsx
src/components/Search/SearchView.tsx
src/components/Search/SelectedRevisionItem.tsx
src/hooks/useFetchCompareResults.ts
src/reducers/CompareResults.ts
src/thunks/compareResultsThunk.ts
src/types/state.ts

Results: Integrate results data

---

src/__tests__/CompareResults/beta/ResultsView.test.tsx
src/__tests__/CompareResults/beta/SearchInput.test.tsx
src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/SearchResultsList.test.tsx
src/__tests__/Search/SearchView.test.tsx
src/__tests__/Search/SelectedRevision.test.tsx
src/__tests__/Search/fetchRecentRevisions.test.tsx
src/__tests__/Search/fetchRevisionByID.test.tsx
src/__tests__/Search/fetchRevisionsByAuthor.test.tsx
src/__tests__/Snackbar.test.tsx

In this PR `title` prop is added to the instances of `<ResultsView/>` and `<SearchView/>` in tests.
_These changes address typeScript errors due to missing `'title'` prop for `ResultsView` and `SearchView` in unit tests, a detail that was missed in the [preceding PR](https://github.com/mozilla/perfcompare/pull/512) resulting in TypeScript errors encountered on running **npm run tsc** in terminal_.

Add 'title' prop in tests

---

src/components/CompareResults/beta/ResultsTable.tsx
src/reducers/ComparisonSlice.ts

This PR is a follow up for PR #507  and addresses [the comment about memoized selector](https://github.com/mozilla/perfcompare/pull/507#discussion_r1296149027) for processing results in Compare Results view.
[Jira Ticket PCF-288](https://mozilla-hub.atlassian.net/browse/PCF-288)

PCF-288 Add selectProcessedResults with memoization

---

.circleci/config.yml

The goal is to split the big job into separate ones, so that they can run in parallel. I did it especially so that adding the typescript check wouldn't make the overall CI run too long.

Configure several jobs in CircleCI and remove the nightly job

---

src/components/CompareResults/beta/RevisionSelect.tsx
src/reducers/ComparisonSlice.ts

This PR is a follow up for #516 to address the [comment](https://github.com/mozilla/perfcompare/pull/516#discussion_r1297358956) about adding memoized select for newRevisions in all revisions dropdown
[Jira ticket](https://mozilla-hub.atlassian.net/browse/PCF-290)

PCF-290 Create memoized selector for populating all revisions dropdown

---

src/__tests__/CompareResults/beta/RevisionSelect.test.tsx
src/__tests__/CompareResults/beta/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/beta/RevisionHeader.tsx

This PR is a follow up for #507 to address the [comment](https://github.com/mozilla/perfcompare/pull/507#discussion_r1290110332) about removing the data-testid
[Jira ticket](https://mozilla-hub.atlassian.net/browse/PCF-289)

PCF-289 Remove data-testid for TableRow in RevisionHeader

---

src/components/CompareResults/beta/ResultsView.tsx

It is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1851048.
- On the initial results view render the store is populated using the data from the URL. These changes ensure that the store is populated with the framework included in the URL.    
- It is achieved with an `updateFramework` action, that is dispatched with the framework param from the URL in `results view`.

Results: Fix framework reverting to 'talos' on page render

---

src/__tests__/CompareResults/ResultsView.test.tsx
src/__tests__/CompareResults/__snapshots__/SearchInput.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/fetchCompareResults.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchComponent.test.tsx.snap
src/components/CompareResults/DownloadButton.tsx
src/reducers/ComparisonSlice.ts

It is a solution for https://bugzilla.mozilla.org/show_bug.cgi?id=1845985.   
- Implemented a `fileName` selector.
- Used `createSelector()` and `React.memo()` to ensure the state is only recalculated when changed.
- Used `blob` instead of putting all the data inside the URL.
- Blob is generated programatically when the user clicks the "Download JSON" button.

Results: Enable "Download JSON" button (Follow up)

---

webpack/webpack.common.js

It is a solution for https://bugzilla.mozilla.org/show_bug.cgi?id=1856337
- Specified the favicon in webpack config.

Fix: favicon not showing on deploy

---

src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SearchInput.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/fetchCompareResults.test.tsx.snap
src/components/CompareResults/DownloadButton.tsx
src/components/CompareResults/ResultsHeader.tsx
src/components/CompareResults/SearchInput.tsx

This PR removes search box from the ui until later implementation.
Add small styling for `Download json` button

PCF-317 Search box is disabled

---

src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/components/Search/FrameworkDropdown.tsx
src/utils/helpers.ts

It is a solution for https://bugzilla.mozilla.org/show_bug.cgi?id=1852292
- `sortFrameworks()` function is implemented.
- Frameworks are sorted alphabetically

Sort frameworks in framework dropdown list

---

src/__tests__/CompareResults/ResultsView.test.tsx
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/ResultsView.tsx
src/components/Search/SelectedRevisionItem.tsx
src/hooks/useSelectedRevisions.ts
src/reducers/SelectedRevisionsSlice.ts

This  PR fulfills [Results: In edit mode, close buttons for selected revisions are broken](https://mozilla-hub.atlassian.net/browse/PCF-344). 
Note that the save and cancel bugs in edit mode will be taken care of in a separate PR. 
Also, I removed some fetch code in the Results View because I initially placed it in a separate, now deleted file but that will be taken care of in Julien's patch. I'll be glad to return it though.

fix for close buttons in edit mode

---

package-lock.json
package.json
src/components/App.tsx

This has 2 commits:
* commit 1: simply update react-router-dom to the latest version
* commit 2: switch to the new API with the `RouterProvider`. This changes nothing to the current behavior but is a prerequisite to the rest of the work.

Update react-router-dom to its latest version and use the new API

---

src/components/Search/SearchComponent.tsx
src/components/Search/SearchInput.tsx

This contains 2 commits that can be looked at independently:
Commit 1:
* This changes the `mousedown` event handler that controls the hiding of the recent revisions dropdown when clicking elsewhere. Previously it also contained some code to display it, but that wasn't used... It also simplifies the check that the user clicks elsewhere.
* This simplifies the way that the search input notifies its parent about the focus event: instead of passing the `setFocused` function coming from `useState`, we just pass a callback that will be called when focus happens.
Commit 2: changes the state name about the fact that the dropdown is displayed or not, to better reflect that. For example we could have the input focused, press Escape, and then the dropdown would be hidden... but the focus would still …

Change a bit how the recent revisions dropdown handling works

---

src/__tests__/CompareResults/RevisionRow.test.tsx
src/__tests__/helpers.test.ts
src/components/CompareResults/RevisionRow.tsx
src/resources/Strings.tsx
src/types/state.ts
src/utils/helpers.ts

Selecting a testing framework other than talos along with selecting mozilla central repo for comparison breaks the app.
- In `RevisionRow` component we use `<plateformIcon/>` element to show the platform icon. On rare ocasion the icon is missing or unspecified however an invalid react element is still generated, breaking the app
Used a ternary operator to check if the `platformInfo.shortName` is present as this is a reliable value to check if the platform icon is  going to be a valid react element or not.
`{platformInfo.shortName ? <PlatformIcon /> : 'Unspecified'}`
If the platform icon is not present we handle it by adding "Unspecified" string. 
**Julien's update:** I changed a few things to the original patch:
* I moved `getPlatformInfo` from `helpers.js` to `RevisionRow`
* I moved the …

Results: (Bug Fix) In RevisionRow handle case when the platform icon is not present

---

src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/TableContent.tsx

This PR addresses [PCF-322 White table row corners in dark mode](https://mozilla-hub.atlassian.net/browse/PCF-322). It removes the white corners.
Before and after

PCF-322 White table row corners in dark mode

---

.eslintrc.js
package-lock.json
package.json
src/__tests__/App.test.tsx
src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/SearchResultsList.test.tsx
src/__tests__/Search/SearchView.test.tsx
src/__tests__/Snackbar.test.tsx
src/__tests__/helpers.test.ts
src/__tests__/utils/setupTests.ts
src/__tests__/utils/test-utils.tsx

I continued working on improving our tooling setup, by using the Firefox Profiler as an example.
In this PR I'm adding these plugins:
* [eslint-plugin-testing-library](https://github.com/testing-library/eslint-plugin-testing-library)
* [eslint-plugin-jest-dom](https://github.com/testing-library/eslint-plugin-jest-dom)
* [eslint-plugin-jest-formatting](https://github.com/dangreenisrael/eslint-plugin-jest-formatting)
I also changed a bit the existing configuration.
I looked at adding the [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks) plugin, but it's showing too many errors around our effects. I'd like to finish #582 and friends before we enable this, to make it easier.
Please do not review the few first commits because I based this PR on top of #584 to …

Add more eslint plugins and enable some new rules

---

jest.config.ts
src/__tests__/CompareResults/ResultsView.test.tsx
src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/SearchContainer.test.tsx
src/__tests__/Search/SearchView.test.tsx
src/__tests__/utils/setupTests.ts

This also removes the running of all timers at the end of some tests, that were working around the faulty setup.
I noticed this issue while working on another patch, and decided to extract it.

Fix the setup of jest fake timers so that they don't run unexpectedly

---

src/__tests__/App.test.tsx
src/__tests__/CompareResults/ResultsTable.test.tsx
src/__tests__/CompareResults/ResultsView.test.tsx
src/__tests__/CompareResults/RevisionRow.test.tsx
src/__tests__/CompareResults/RevisionSelect.test.tsx
src/__tests__/CompareResults/SearchInput.test.tsx
src/__tests__/CompareResults/TableHeader.test.tsx
src/__tests__/CompareResults/fetchCompareResults.test.tsx
src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/SearchContainer.test.tsx
src/__tests__/Search/SearchResultsList.test.tsx
src/__tests__/Search/SearchView.test.tsx
src/__tests__/Search/SelectedRevision.test.tsx
src/__tests__/Search/fetchRecentRevisions.test.tsx
src/__tests__/Search/fetchRevisionByID.test.tsx
src/__tests__/Search/fetchRevisionsByAuthor.test.tsx
src/__tests__/Snackbar.test.tsx
src/__tests__/hooks/useFetchCompareResults.test.tsx
src/__tests__/hooks/useHandleChangeSearch.test.tsx
src/__tests__/utils/setupTests.ts
src/__tests__/utils/test-utils.tsx

Before this patch, we have 2 different render functions: `render` and `renderWithRouter`. We also have a `StoreProvider` that's just `react-redux`'s `Provider` pre-configured, that we use in some hooks-related test files.
The 2 render functions are "created" in `beforeEach` and exposed by `setupTests`. Instead of "creating" them, in this patch they're now defined directly, and they can be imported directly from `test-utils` in the test files. The goal is that it's now easier to create new flavors for these functions, that I'd like to use in #582.
The `store` object is imported from `setupTests` instead of being passed as a parameter. I considered creating it in the  `render` functions (possibly as a default parameter, so that we could pass another store if needed) and returning it, but …

Simplify how the render functions are defined and used in test files

---

src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SearchInput.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/fetchCompareResults.test.tsx.snap
src/components/CompareResults/ResultsTable.tsx

This PR addresses [PCF-362 Fix dark mode on results table](https://mozilla-hub.atlassian.net/browse/PCF-362).
The table background is the same as the page background. Below there is a before and after.

PCF-362 Fix dark mode on results table

---

package-lock.json
package.json
public/_redirects
src/components/App.tsx
webpack/webpack.common.js

Please look at the last commits only, as the first commits are #582.
This does these (fairly unrelated) things:
* Commit 1: instanciate the router outside of the react tree, like advised by the react router documentation, so that we don't regenerate one at each rerender. This should improve performance.
This wasn't so easy before because we had to get the theme from a hook and pass it as a parameter, but thanks to #590 this is now possible.
* Commit 2: this uses [`createBrowserRouter`](https://reactrouter.com/en/main/routers/create-browser-router) instead of [`createHashRouter`](https://reactrouter.com/en/main/routers/create-hash-router).
This makes more natural URLs without the `#` character. https://perf.compare/#/compare-results will be now just https://perf.compare/compare-results. Or …

React-router use: instanciate the router outside of the react tree, and stop using hashes for our URLs

---

src/__tests__/App.test.tsx
src/__tests__/__snapshots__/App.test.tsx.snap
src/components/App.tsx
src/components/CompareResults/ResultsView.tsx
src/components/Search/SearchContainer.tsx
src/components/Search/SearchView.tsx
src/components/Shared/LinkToHome.tsx
src/components/Shared/PageError.tsx
src/components/Shared/PerfCompareHeader.tsx
src/styles/Header.ts
src/styles/SearchContainerStyles.ts

Please look only at the last commits that are not prefixed with a mention.
The 2 first commits are preparatory to the Error Boundary component. They make it easier to have a similar visual design.
Commit 3 adds a simple error boundary and configures it with the router.
Commit 4 adds new tests for the router and the error boundary.
Most of the remaining missing coverage will be covered when I'll work on fetching the recent revisions using the react router, that's why I didn't cover them here.
You can test the error boundary by requesting with wrong parameters, for example:
* no parameters => https://deploy-preview-600--mozilla-perfcompare.netlify.app/compare-results
* no baseRepo => https://deploy-preview-600--mozilla-perfcompare.netlify.app/compare-results?baseRev=foo
* not the same …

Add an Error Boundary for the results page, and add more tests around the react router behavior

---

package-lock.json
package.json

This fixes a performance issue with getComputedStyle, which is used heavily by testing-library's `queryAllByRole` (which is used by all `*ByRole` queries).
This upgrades jsdom from v19 to v22.
This version of jsdom (v22) includes [this fix](https://github.com/jsdom/jsdom/pull/3482).
On my machine, running all tests goes from 25 seconds down to 14 seconds with this simple update. I expect that will be even better on slower machines having less cores.
Note: this installs some other jest packages with a newer version too, in parallel to our current version. I think it's OK. We can update to v30 when the stable version is released.

Use a more recent jsdom with Jest

---

src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/styles/ExpandableRow.ts

Closes this issue: [Non-expanded rows should not render at all (or use display: none)](https://mozilla-hub.atlassian.net/browse/PCF-359)

set non exapnded row to display none

---

src/__tests__/utils/fixtures.ts
src/components/Search/CompareWithBase.tsx
src/components/Search/SearchComponent.tsx
src/components/Search/SearchContainer.tsx
src/components/Search/SearchResultsList.tsx
src/components/Search/SearchResultsListItem.tsx
src/components/Search/SelectedRevisionItem.tsx
src/components/Search/SelectedRevisions.tsx
src/hooks/useCheckRevision.ts
src/hooks/useSelectedRevisions.ts
src/logic/treeherder.ts
src/reducers/SearchSlice.ts
src/reducers/SelectedRevisionsSlice.ts
src/thunks/searchThunk.ts
src/types/api.ts
src/types/state.ts
src/utils/helpers.ts

This was confusing me a lot. Indeed in the code base, the term "revisionsList" was used for both a Changeset and a list of Changesets (`RevisionsList[]`).
So I think the term Changeset is more idiomatic. This is how Firefox developers call this object.
For example on hg.mozilla.org: https://hg.mozilla.org/mozilla-central/pushloghtml or https://hg.mozilla.org/integration/autoland/rev/64e14543839c59fc9fc3d71a1cc60507bb9c7064
Note that 64e... is the changeset's revision, so it's exactly the same object we have here.

Rename RevisionsList to Changeset

---

src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/components/CompareResults/ResultsView.tsx
src/components/Search/CompareWithBase.tsx
src/components/Search/SearchComponent.tsx
src/components/Search/SearchContainer.tsx
src/components/Search/SearchResultsList.tsx
src/components/Search/SelectedRevisionItem.tsx
src/components/Search/SelectedRevisions.tsx

Please look at the last commit only, as the first one is #617. Also of course I can rebase and change it if we decide to use another type name than `Changeset`.
This is a small simplification of how we deal with the repository information.
Indeed we were always computing them from the items before setting the state anyway, so it's easier to compute them when and where needed. This simplifies some code.

Do not store repository information in the CompareWithBase state

---

src/components/Search/SearchComponent.tsx
src/components/Search/SearchOverTime.tsx
src/components/Search/SearchResultsList.tsx
src/components/Search/SearchResultsListItem.tsx

Please look at the last 2 commits only.
This removes some unused props for `SearchComponent` and `SearchResultsListItem`.

Small cleanup for SearchComponent

---

src/components/Search/CompareWithBase.tsx

Please look at the last commit only.
Here is the STR:
1. Go to https://beta--mozilla-perfcompare.netlify.app/
2. Pick a base rev, and 3 "new revs".
3. Press "Compare"
4. Reload the page (important)
5. Edit the new revs
6. Try to uncheck the first one from the search results list.
=> result: the last one is unchecked instead of the first one
When unchecking one element, the executed operation to find the index is:
```js
revs.indexOf(item)
```
Where `revs` contains the currently selected items, and `item` is the item we just clicked. 
The problem is that the object `item` isn't inside `revs`... an identical object is present, but not the exact same object with the same reference. As a result `indexOf` doesn't find the object... and returns `-1`.
Then `-1` is passed to `splice`, which …

Fix that the wrong item is unselected in some situations

---

src/components/Search/SearchComponent.tsx
src/components/Search/SearchOverTime.tsx
src/components/Search/SearchResultsList.tsx

This was done for `SearchInput` in a previous PR, but `SearchResultsList` used `hasNonEditableState` for more things before #626. After #626 we can change its name so that it's more descriptive.
Please look at the last commit only.

Change SearchResultsList's prop 'hasNonEditableState' to 'compact'

---

src/__tests__/Search/SearchContainer.test.tsx
src/__tests__/Search/SearchView.test.tsx
src/components/CompareResults/ResultsView.tsx
src/components/Search/CompareWithBase.tsx
src/components/Search/SearchComponent.tsx
src/components/Search/SearchDropdown.tsx
src/components/Search/SearchInput.tsx
src/components/Search/SearchOverTime.tsx
src/components/Search/SearchView.tsx
src/components/Search/SearchViewInit.tsx
src/reducers/SearchSlice.ts
src/types/state.ts

The goal is to make `SearchContainer` and all other components in the tree more self-contained that they were before.
This also moves SearchViewInit to CompareWithBase. But this is only
temporary because this component will be removed later.

Move the repository information from Redux to a local state in CompareWithBase

---

src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/components/Search/SearchComponent.tsx
src/components/Search/SearchInputAndResults.tsx
src/components/Search/SearchOverTime.tsx

Extracting these 2 components into a separate comment makes sense in terms of component responsibilities. Indeed the SearchInput controls its Dropdown. Using a component to contain both makes it possible for this component to keep all the necessary state to control this behavior This is also common code for both `SearchOverTime` and `SearchView`, so it makes sense to extract it.
Please look at the two last commits only.
Commit 1: this extracts the common code to a separate component
Commit 2: this changes this component to make it more generic, so that it works the same for both CompareWithBase and CompareOverTime, without relying on class names. There are a bunch of snapshot changes because this adds a new container to the pair `SearchInput` / `SearchResultsList`, if you look at them by …

 Extract a component `SearchInputAndResults` for the `SearchInput` and its dropdown 

---

src/__tests__/CompareResults/ResultsView.test.tsx
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/RevisionRow.tsx
src/styles/ExpandableRow.ts

In this PR, the non expanded rows are not rendered unless `expanded` is true. Ran the profiler and it reduces the jank significantly especially in my compare-over-time patch. Closes https://mozilla-hub.atlassian.net/browse/PCF-439

Donot render non expanded rows

---

src/__tests__/Search/CompareWithBase.test.tsx
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/components/CompareResults/ResultsView.tsx
src/components/CompareResults/loader.ts
src/components/Search/CompareWithBase.tsx
src/components/Search/SearchComponent.tsx
src/components/Search/SearchContainer.tsx

In the same way that we pass down the rev information for the selected revs in the results list, it makes sense to pass down the repo info so the repo drop-down is already set to the committed repo in the Results view edit section

pass down repo info and adjusted tests

---

src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
src/components/Search/CompareButton.tsx
src/components/Search/EditButton.tsx
src/components/Search/SaveCancelButtons.tsx
src/components/Search/SelectedRevisionItem.tsx
src/styles/CompareCards.ts
src/styles/SelectedRevsStyle.ts
src/theme/components.js

It's probably easier to look at commits separately.
* Commit 1: uses IconButton instead of Button for some of our icons -- namely the "edit" button and the "remove revision" button. This makes these buttons much nicer in the process, especially on hover. Note that this was needed for setting the variant by default in commit 2, that's why I included it in this PR too.
* Commit 2: set some defaults for all buttons: variant = contained so that they look like button, and disableElevation to remove box shadows. I think that the shared styles do some of "variant = contained" too and we might want to simplify them later, but I didn't want to do that now. (see https://mui.com/material-ui/customization/theme-components/#theme-default-props about this -- we could also add `disableRipple` if we want …

Use IconButton for nicer "edit" and "remove revision" icons, and set default appearance for all buttons

---

src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/__snapshots__/App.test.tsx.snap
src/components/CompareResults/DownloadButton.tsx
src/components/CompareResults/SearchInput.tsx
src/components/Search/CompareButton.tsx
src/components/Search/SaveCancelButtons.tsx
src/styles/Buttons.ts
src/styles/Header.ts
src/theme/components.js
src/theme/protocolTheme.ts

This PR started as a simple nit PR but ended up doing some more. This changes the button using the "primary" and "secondary" colors, I didn't touch to the dropdown styles though because I didn't need that... maybe later ;-)
There are 4 commits then:
* Commit 1: Small nit regarding the compare button
* Commit 2: Use MUI's palette for primary buttons
* Commit 3: Use MUI's palette for secondary buttons
* Commit 4: Update tests
More comments in the commits themselves.
There should be no visible change with this PR besides the Download Button. That one now works with dark mode, and also gains a box shadow that should be removed with #665.

Rework styles for buttons using the palette from Material UI

---

src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/components/CompareResults/OverTimeResultsView.tsx
src/components/CompareResults/ResultsView.tsx
src/components/Search/CompareOverTime.tsx
src/components/Search/CompareWithBase.tsx
src/components/Search/SearchComponent.tsx
src/components/Search/SearchContainer.tsx
src/components/Search/SearchOverTime.tsx

The prop `hasNonEditableState` is confusing because of the double negative when using the false boolean. Let's make it positive, `hasEditableState`, so there's less cognitive load.

change the prop name to make it less confusing

---

src/components/Search/CompareWithBase.tsx

This PR sets the view back to read-only post click of the Compare button in the Results View edit mode. Closes https://mozilla-hub.atlassian.net/browse/PCF-443

reset view post submit

---

src/__tests__/Search/SearchView.test.tsx
src/components/Search/SearchInputAndResults.tsx

There was 2 issues:
1. The search function and its debounce version were being recreated at
each render. As a result it wasn't debounced and a new request was
being sent for each keystroke, albeit after half a second.
2. The ID used to know if the received response is for latest search
wasn't incremented at the right place. As a result some reponses
weren't ignored where they should have been.
This first commit fixes both issues, by using useCallback and incrementing the search id in the right place.
The second commit is a small correctness issue where `handleEscKeypress` wasn't memoized. I think it wasn't doing any problem but it's more consistent with the other function `handleDocumentMousedown`.
Finally the 3rd commit fixes a bunch of issues with the existing test for the SearchView. …

Properly debounce the search function, and increment the ID

---

src/components/CompareResults/RetriggerButton.tsx
src/components/CompareResults/RevisionRow.tsx

This PR fullfills a part of [PCF-432 Implement the "login" intermediate popup if credentials are not available](https://mozilla-hub.atlassian.net/browse/PCF-432)
It adds the storage event that will later be used to trigger some action after the localStorage saved the userToken/userCredentials.

PCF-432 Subtask Create RetriggerButton component, add storage event

---

.eslintrc.js
package.json
src/__tests__/CompareResults/OverTimeResultsView.test.tsx
src/__tests__/CompareResults/ResultsTable.test.tsx
src/__tests__/CompareResults/ResultsView.test.tsx
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/Search/SelectedRevision.test.tsx
src/components/CompareResults/RevisionHeader.tsx

The problem is that `"".split(" ")` produces an array with one empty string. As a result we were adding an empty box.
When I wanted to add a test I realized that the test for ResultsTable was incorrect and was always generating an empty table. I fixed that as well. I ordered the commits so that the changes are well visible.
I also added 2 commits to change the eslint configuration:
1. so that eslint warns us about unused "disable" directives. This is useful for cleanup.
2. so that eslint doesn't warn anymore when somebody uses the "not null assertion" (the `!`) in tests only.
I reconize that this makes a PR with several quite unrelated things in it, I hope that the fact they're separated in several commits makes it OK enough. I did it this way because I used the eslint changes in the …

Do not add extra options flags if there are no extra options

---

package-lock.json
package.json
src/__tests__/CompareResults/ResultsTable.test.tsx
src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/ResultsTable.tsx
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/TableHeader.tsx
src/resources/Strings.tsx
src/types/state.ts
src/types/types.ts
src/utils/platform.ts

This implements filtering by column.
The initial commits in the PR are #678 so please don't look at them here.
Then the commits are:
1. update the user-event library: indeed the new version expose a type that I'd like to use in the tests
2. Some moving around of types. This also removes some types that are not used.
3. Some more refactoring around how the short platform name and icon are computed. Indeed I want to reuse this in the filtering.
4. This is the meat of the PR, where the implementation for filtering happens. I tried to implement this so that we'd loop over the results only once for filtering. Ideally we'd do the "processResults" in the same loop too, but decided to leave this for future work, also to keep the code cleaner.
5. This changes the "expand icon" to a "filter icon". …

Filter columns

---

src/__tests__/TaskclusterAuth/TaskclusterCallback.test.tsx
src/components/CompareResults/RetriggerButton.tsx
src/components/TaskclusterAuth/loader.ts
src/logic/credentials-storage.ts
src/logic/taskcluster.ts

I moved around some code to make the authentication process more self contained and easier to work with.
Now the call to `getTaskclusterAccessToken` will always return an access token: sometimes it will return the one stored in localStorage, sometimes it will trigger the taskcluster authentication.
I added a few TODO to be done in future PRs too.

Move around some code so that the token retrieval is more self-contained

---

src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/TableContent.tsx

Ran the profiler and it reduces jank
This PR closes the following issue:[The typestyle calls in the RevisionRow are too costly]( https://mozilla-hub.atlassian.net/browse/PCF-448)
Profiles: [beta](https://share.firefox.dev/46bM2lb) / [deploy preview](https://share.firefox.dev/3y28fFM)
To test:
1.) open PR deploy link: https://deploy-preview-689--mozilla-perfcompare.netlify.app/ 
2.) Select a base revision and a new revision(s) from the `Compare with a base` component
3.) Select the browsertime testing framework - heavy testing framework where you can see the most change in performance
3.) Click the `Compare` button
4.) The results page should perform better re loading vs the most current beta link: https://beta--mozilla-perfcompare.netlify.app/) / [deploy …

moved typestyle calls outside the component

---

src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/components/Search/CancelAndCompareButtons.tsx

A quick PR to hide the compare button on the initial load of the results page. Make it visible after user hits the `Edit entry `button.
Closes the following issue: https://mozilla-hub.atlassian.net/browse/PCF-411

Hide compare button on initial results page load

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/RevisionRow.tsx

I was looking at the results page and I had no idea what "B" and "N" was first in the results view. I had to go into the code to read the variable to understand.
This patch adds a `title` to these letters so people can hover over them to understand what they are.
Also it didn't have an adequate spacing between those values. Looked at the figma file and it does indeed have spacing. So I added it as well.
Before:
After:

Add some spacing between total runs and explain the letters with a title

---

src/components/CompareResults/Retrigger/CenteredModal.tsx
src/components/CompareResults/Retrigger/RetriggerConfigModal.tsx
src/components/CompareResults/Retrigger/RetriggerSignInModal.tsx
src/theme/components.js

This fixes one issue that @canova reported to me: the various selection dropdowns were showing a grey backdrop behind them when opened:
I quickly considered that https://github.com/mozilla/perfcompare/pull/684/commits/15de4c6794737f92c9ddc07d36197719ef009f30 would be the issue. Indeed the selection dropdowns also insert a backdrop, and that change would make them all grey, while before they were transparent.
I tried to change it for just Modals... but turns out the selection dropdowns also use a Modal to position themselves!
Then in https://mui.com/material-ui/api/modal/, I've seen this small sentence:
> If you are creating a modal dialog, you probably want to use the [Dialog](https://mui.com/material-ui/api/dialog/) component rather than directly using Modal.
I missed it when I …

Use the Dialog component instead of the Modal component for the retrigger modals

---

src/components/CompareResults/DownloadButton.tsx

I was looking at the performance of the results page with the react profiler tool, and found that the DownloadButton component was using more time than it should have. So here is a small patch to fix that.
I tested manually that clicking the button was still responsive, even with the "browsertime" framework selection.
There are existing tests covering this piece of functionality that didn't need any change.

Generate the results blob on click instead of at render time

---

package-lock.json
package.json
src/components/CompareResults/loader.ts
src/components/CompareResults/overTimeLoader.ts
src/logic/treeherder.ts

The goal for this patch is to memoize the result of fetching the revision information for specific revisions.
This has 2 commits:
1. Commit 1 is a preparation commit: this creates a specific function for this operation, so that it can be memoized in step 2.
2. Commit 2 uses the library https://github.com/planttheidea/moize to implement the memoization itself. I looked at many libraries and decided to use this one because of its simple yet effective API, with all the features we need here. Especially it makes it easy to use an option object for the function, and configure the number of calls to be memoized.
It can also be configured with an expiration, which could be useful for us later if we decide to use it for the results (maybe), and the cache can also be controlled from outside, which …

Memoize the fetches for the revision information

---

src/__tests__/CompareResults/RevisionRow.test.tsx
src/components/CompareResults/ResultsMain.tsx
src/components/CompareResults/ResultsTable.tsx
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/TableContent.tsx
src/components/CompareResults/loader.ts
src/components/CompareResults/overTimeLoader.ts
src/types/state.ts

This issue is especially visible when changing the framework... but only after removing the `reloadDocument` property, which I'm not doing in this deploy preview, so you won't be able to check this from the deploy preview. You can checkout the pull request locally and remove `reloadDocument` to check for yourself.
The issue is that the table is rerendered again even though nothing changed yet. From the react profiler, I found that it's rerendered because "context changed", that is the context from react router. This happens when using `useLoaderData` (see the issue I filed in https://github.com/remix-run/react-router/issues/11864).
So I fixed this through 2 commits:
1. Commit 1 is the simplest: it uses the "children function" style of `Await` so that `ResultsTable` can be a memoized …

Avoid a spurious rerender when changing the framework (and other things related to the router)

---

src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/RevisionSelect.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SearchInput.test.tsx.snap
src/components/CompareResults/DownloadButton.tsx
src/components/CompareResults/ResultsMain.tsx
src/components/CompareResults/RevisionSelect.tsx
src/components/CompareResults/SearchInput.tsx
src/components/Shared/FrameworkDropdown.tsx

This PR fixes the header styles for the Results Table using `Grid`

Used Grid to fix results header

---

@types/taskcluster-client-web.d.ts
src/__tests__/CompareResults/Retrigger.test.tsx
src/__tests__/CompareResults/__snapshots__/Retrigger.test.tsx.snap
src/__tests__/utils/setupTests.ts
src/components/CompareResults/Retrigger/RetriggerButton.tsx
src/logic/taskcluster.ts
src/resources/Strings.tsx

This dislpays a notification for each retrigger request: one for base and one for new. I tried to merge them, but found that it looked better with 2 individual notifications. Please tell me if you think otherwise :-)
Also updated tests.
Do not look at the first commits, they are coming from Andra's PR #695 because my tests build on them.
I tested from [this results page](https://deploy-preview-703--mozilla-perfcompare.netlify.app/compare-results?baseRev=c6bbeb21b9650e398bd364eba25a1e61bd285a19&baseRepo=mozilla-central&framework=1) but retriggers don't work from a deploy preview, so if you want to try you need to checkout the pull request on your local computer.

Display a notification to the user after the retrigger request is sent

---

src/components/CompareResults/DownloadButton.tsx
src/components/CompareResults/ResultsMain.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsMain.tsx
src/components/CompareResults/loader.ts
src/components/CompareResults/overTimeLoader.ts
src/components/Search/CompareWithBase.tsx

This is ready for review !
Commit 1 is #708.
Commit 2 is the thing that you did in other PRs: remove `defer`
Commit 3 adds a key like mentioned in the comment below. Hopefully the comments in the code should be clear but tell me if we need more.
Commit 4 moves the results table header out of the Suspend area, so that it's visible while the data loads.
Commit 5 is a small fix for the types returned by the loaders.
Commit 6 fixes the DownloadButton after commit 4: because it's now outside of the Suspense/Await, it gets a promise in the normal results page, but the non-promise in the subtests page. This commit makes it work in both cases.

Better use Suspense to get a spinner when data is loading

---

src/components/CompareResults/CommonGraph.tsx
src/components/CompareResults/Distribution.tsx
src/components/CompareResults/GraphDistribution.tsx
src/components/CompareResults/RunValues.tsx

I've been testing with [this URL](https://deploy-preview-709--mozilla-perfcompare.netlify.app/compare-results?baseRev=c6bbeb21b9650e398bd364eba25a1e61bd285a19&baseRepo=mozilla-central&newRev=70728a2fa4a234daf6c2ce7278965031bc2565a6&newRepo=mozilla-central&framework=1) (compare with the [beta branch](https://beta--mozilla-perfcompare.netlify.app/compare-results?baseRev=c6bbeb21b9650e398bd364eba25a1e61bd285a19&baseRepo=mozilla-central&newRev=70728a2fa4a234daf6c2ce7278965031bc2565a6&newRepo=mozilla-central&framework=1)) that has a few retriggers.
I tweaked a few things with this patch (each line is a separate commit):
* By using triangles instead of circles, we get a sharper shape, and therefore it's easier to distinguish them when they're closer
* all graphs are now on the same scale, which …

Tweak styles and characteristics of the charts

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/RevisionRow.tsx

Fixes [Bug 1913290](https://bugzilla.mozilla.org/show_bug.cgi?id=1913290).
This PR adds background colors and svg icons to the "Improvement" and "Regression" labels in the results table.
Before:
After:
Dark mode:

Make the improvement/regressions eaier to find by adding some colors and icons

---

src/styles/SelectList.ts

This fixes [Bug 1913699](https://bugzilla.mozilla.org/show_bug.cgi?id=1913699).
Please see the STR that I mentioned in the bug. `SelectList` selected item active and selected background colors on dark mode were still using the light mode's color and that's why they were hard to read on a white text. This PR fixes those colors so it's easier to read them, and the UI colors are more consistent on dark mode.
Before:
After:

Fix SelectList item active and selector background colors on dark mode

---

src/components/CompareResults/SubtestsResults/SubtestsResultsMain.tsx

Follow up for [adding retrigger functionality for subtests](https://github.com/mozilla/perfcompare/pull/711#pullrequestreview-2248064981)

Transition subtest header to grid layout

---

src/components/CompareResults/CommonGraph.tsx

This was bothering me for some time.
The problems:
* to compute the KDE graph, I was using the prop "min and max". The problem is that then we don't see well the contributions of the leaf most or right most points. This is more visible after #734 but was already visible before.
* when there's just one point (such as when looking at just one revision that has just one run), the graph doesn't show up, I think because the bandwidth is 0. This is visible after #734.
So this patch fixes both these issues.
Here are some before/after:
Before / After
[beta branch](https://beta--mozilla-perfcompare.netlify.app/compare-results?baseRev=d5b7f825041b9d72eaadd25d879034d1c121e449&baseRepo=mozilla-central&framework=1) / [deploy preview](https://deploy-preview-740--mozilla-perfcompare.netlify.app/compare-r …

Increase range of the kde graph and other tweaks

---

src/__tests__/CompareResults/SearchInput.test.tsx
src/components/CompareResults/ResultsMain.tsx
src/components/CompareResults/SearchInput.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsMain.tsx
src/hooks/useRawSearchParams.ts

I tried to make it possible to update the URL search parameters without re-rendering the whole page. Unfortunately because of the limitation of react-router, it's not possible on that level. 
I added a custom hook to handle this behavior instead of their hook. I only added it for the search term in this PR, but the other filtering options can be added similarly.
There are a few things to consider though:
- Since the browser navigation still handled by react-router, browser back/forward navigation still re-renders stuff. But that's maybe okay?
- Using `pushState`/`replaceState` while using react-router is not recommended usually by this library. But I'm not worried about this tbh, I think the first item is more important.
- I'm using `pushState` now, but the hook also supports …

Persist the search term in the url

---

src/__tests__/CompareResults/RevisionRow.test.tsx
src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/ResultsTable.tsx
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsTable.tsx
src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsTableContent.tsx
src/components/CompareResults/TableContent.tsx
src/components/CompareResults/TableHeader.tsx

This PR has 4 commits:
1. adds colors to the subtests view.
2. a small performance-related change about how we deal with the dark and light styles in the subtests page.
3. change how the grid's columns are configured -- instead of an hardcoded value, it comes from the cellsConfiguration. This makes it easier to do different adjustments in the subtests view vs the main view.
4. adjusts a little bit the layout of the results table so that the columns look more aligned.
I did all these changes here because without these changes, the color boxes in the subtests view was moving everything and this wasn't nice at all.
[Production](https://perf.compare/compare-results?baseRev=3cb77efac4ded0c08c36473cf7fac371ad39eaf8&baseRepo=try&newRev=90a817d001629308f4d5acdc2b6317c0e39a82da&newRepo=try&framewor …

Add colors to subtests and small layout changes

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/ResultsControls.tsx
src/components/CompareResults/ResultsMain.tsx
src/components/CompareResults/ResultsTable.tsx
src/components/CompareResults/TableContent.tsx
src/components/CompareResults/TableHeader.tsx
src/components/CompareResults/TableRevisionContent.tsx

Problem statement: after the user scrolled down, then the search and filter are out of sight and it can be diffcult to find them back if the page is long. After #712 Full Page Search (Ctrl-F) doesn't work anymore, so it starts to be a bigger problem.
[deploy preview](https://deploy-preview-719--mozilla-perfcompare.netlify.app/compare-results?baseRev=a87b00c4f5cfad5ef2fee563342574340e983619&baseRepo=mozilla-central&newRev=0be9e6fdab7b5eb39e27461cbec046d8a0f9f951&newRepo=mozilla-central&framework=1)
It was much more work than what it looked initially, because the 2 components to make sticky were in very different places and I had to move a lot of code around.
I tried to split it in separate commits. The first commit is #750, I extracted it because it's fairly unrelated to that one. The …

Use position sticky for the headers

---

src/components/CompareResults/Retrigger/RetriggerConfigModal.tsx

As requested by @acreskeyMoz!
I tried using a native select so that you wouldn't have to open the select before selecting the value with the keyboard but I couldn't style it quickly properly, so I kept MUI's version for now.

Increase the maximum amount of possible retriggers to 9

---

README.md

I've completed writing the documentation for PerfCompare and think it would help to add it to our README. I'd like to get input from the whole team if possible. Thanks. 
[PerfCompare Documentation](https://docs.google.com/document/d/1cpQEZXw0M5QjmNL2F1S9NKjWmz6A9Ks7zELVNTXLeB4/edit#heading=h.u62ha0d6mpxl)

PCF 434: Add documentation to ReadME

---

package-lock.json
package.json
src/__tests__/TaskclusterAuth/TaskclusterCallback.test.tsx
src/__tests__/TaskclusterAuth/__snapshots__/TaskclusterCallback.test.tsx.snap
src/components/TaskclusterAuth/TaskclusterCallback.tsx
src/components/TaskclusterAuth/loader.ts
src/logic/taskcluster.ts

Previously, after the user signs in on taskcluster so that they can do a retrigger request, perfcompare displays a blank page while it validates the credentials. This isn't a great experience so this patch adds up some (limited) spice, especially a spinner.
This also adds some more tests and fixes a bug with handling errors properly (and adds a test about that).
Commit 1: updates react-router-dom because this fixes an issue with `Await` in the test (without that there's some infinite loop).
Commit 2: make the taskcluster auth landing page asynchronous with promises and adds the spinner.
Commit 3: changes the structure of the test and simplifies it a bit so that other tests can easily be added.
Commit 4: adds a specific test for the spinner.
Commit 5: fixes the issue with handling errors …

Redesign the landing page after the taskcluster signin

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx
src/styles/Colors.ts
src/theme/protocolTheme.ts

[Jira ticket](https://mozilla-hub.atlassian.net/browse/PCF-425)
This PR adds colorful icons to confidence column (Low, Medium, High).
[deploy link with the example](https://deploy-preview-764--mozilla-perfcompare.netlify.app/compare-over-time-results?baseRepo=mozilla-central&selectedTimeRange=1209600&newRev=9b3deb938fdd67b35a981cf1613a817dfb7eb65f&newRepo=mozilla-central&framework=1)

PCF-425 Add colors and icons for the confidence information

---

src/__tests__/Search/CompareOverTime.test.tsx
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/utils/setupTests.ts
src/components/Search/SearchOverTime.tsx
src/components/Search/TimeRangeDropdown.tsx
src/styles/DropDownMenu.ts
src/utils/format.ts

Solves [Bug 1922027](https://bugzilla.mozilla.org/show_bug.cgi?id=1922027)
This PR enhances the existing time range dropdown in the CompareOverTime UI by displaying specific dates alongside the predefined time range options. This provides users with better clarity on the exact date ranges they are selecting.
Updated the time range dropdown to display specific start and end dates next to predefined options (e.g., "Last 7 days" now shows the exact dates).

Add date range to time range dropdown

---

src/__tests__/CompareResults/ResultsTable.test.tsx
src/__tests__/CompareResults/ResultsView.test.tsx
src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/LinkToRevision.tsx
src/components/CompareResults/RevisionHeader.tsx
src/components/CompareResults/TableContent.tsx
src/components/CompareResults/TableRevisionContent.tsx
src/components/CompareResults/TestHeader.tsx
src/types/state.ts

This pull request implements the grouping of results by test. It is useful when there are at least 2 revisions selected for the "new" range. Before this change, all the tests for the 2nd revision would be rendered after all the tests for the 1st revision.
It's easier to review commit by commit, and I believe it's also easier to review by hiding whitespace changes.
Commits:
1. Simple simplification to make TableContent more readable
2. I noticed that to render a header for a test, we were creating a separate object by reusing the results value. I changed this to use the result object directly.
3. Probably the most complex change. I tried to add comments inline in the project, but please tell me if anything needs to be clarified further.
4. This uses the new structure from commit 3 to …

Group results by tests

---

src/components/CompareResults/ResultsTable.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsTable.tsx
src/hooks/useTableFilters.ts

This is a part of #788 that I was most interested in and that I extracted out. I also used the new hook on the subtests page.
There should be no user-visible change.
This is a refactoring prerequisite to implementing the persisting of the table filters.
[main page on the production server](https://perf.compare/compare-results?baseRev=509ed8685f4554d84912f8b6aa6c14b2228b8065&baseRepo=try&newRev=0a64fa4522419b96e51143f656a94442f7339983&newRepo=try&framework=13) / [main page on the deploy preview ](https://deploy-preview-808--mozilla-perfcompare.netlify.app/compare-results?baseRev=509ed8685f4554d84912f8b6aa6c14b2228b8065&baseRepo=try&newRev=0a64fa4522419b96e51143f656a94442f7339983&newRepo=try&framework=13)
[subtests on production server](https://perf.compare/subtests-compare-results?baseRev=5 …

Extract the table filters into a common hook

---

src/__tests__/CompareResults/ResultsTable.test.tsx
src/components/CompareResults/ResultsTable.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsTable.tsx
src/hooks/useTableFilters.ts

This PR implements the persistence of the column filters as URL parameters.
Here are the individual commits:
1. Initial implementation by @ST-KO in #788 that I wanted to keep as is so that the authorship is preserved.
2. Use the cell configuration so that the values are sanitized, in case a user wants to pass invalid filter values
3. This reverses the logic: instead of persisting the unchecked values, this persists the checked value. It seemed more user-friendly if one user wanted to change the url themselves. Also I think we'll eventually change the state to hold the checked values instead of the unchecked values, so this is consistent with this future implementation.
4. A simple move of functions in a test file, because I didn't want to have it in the same commit as the test change.
5. …

Persist column filters as URL parameters

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/RevisionRowExpandable.tsx
src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx

[Jira ticket](https://mozilla-hub.atlassian.net/browse/PCF-323)
This PR removes the white space when the row is expanded.
[localhost link - results](http://localhost:3000/compare-results?baseRev=c6fee9276fa2d9f298e9a081b5bcf4a8e3797316&baseRepo=mozilla-central&newRev=a635fc061556de8501069d83b02b083892ab2802&newRepo=mozilla-central&newRev=c9170b504cdce7fd51d1934bad32709bea49b112&newRepo=mozilla-central&framework=1)
[localhost link - subtests](http://localhost:3000/subtests-compare-results?baseRev=c6fee9276fa2d9f298e9a081b5bcf4a8e3797316&baseRepo=mozilla-central&newRev=a635fc061556de8501069d83b02b083892ab2802&newRepo=mozilla-central&framework=1&baseParentSignature=301893&newParentSignature=301893)
[deploy link - results](https://deploy-preview-800--mozilla-perfcompare.netlify.app/compare-res …

PCF-323 Expanded row doesn't match the figma design

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
src/components/CompareResults/TableHeader.tsx
src/components/CompareResults/TableRevisionContent.tsx

Fix [Bug 1933586](https://bugzilla.mozilla.org/show_bug.cgi?id=1933586) / JIRA [PCF-577](https://mozilla-hub.atlassian.net/browse/PCF-577).
The problem is outlined in this FAQ on Virtuoso website: https://virtuoso.dev/troubleshooting/#list-does-not-scroll-to-the-bottom--items-jump-around
The problem is that Virtuoso can't measure margins properly, so we have to replace them with paddings, where necessary (basically when margins make the shape of the item bigger).
And this leads to all sort of problems, because while margins of different elements can merge, paddings don't merge. So I had to adjust paddings and margins in a lot of different places.
Especially I changed the margin bottom for the TableHeader component, which applies also to the subtests. But fortunately this also makes the …

Fix the lack of space at the bottom of the results page

---

src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
src/styles/SelectedRevsStyle.ts

[Local Link](http://localhost:3000/compare-results?baseRev=d140333670bcd3103a668a5ec04ed438bb192368&baseRepo=mozilla-central&newRev=250be4ca3c669db9a397456402f68249aa15d8d5&newRepo=mozilla-central&newRev=c0157231377305c8d7c22e452beff7c43fe4e9d7&newRepo=mozilla-central&framework=13&search=foo)
[Deploy link](https://deploy-preview-831--mozilla-perfcompare.netlify.app/compare-results?baseRev=d140333670bcd3103a668a5ec04ed438bb192368&baseRepo=mozilla-central&newRev=250be4ca3c669db9a397456402f68249aa15d8d5&newRepo=mozilla-central&newRev=c0157231377305c8d7c22e452beff7c43fe4e9d7&newRepo=mozilla-central&framework=13&search=foo)
Before
Added `alignItems:flex-start` to the `selectedRevision` style. This was previously removed because we thought it was a default value and shouldn't be added 
Also …

Fix break to revision edit panel layout

---

src/__tests__/CompareResults/SubtestsResultsView.test.tsx
src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
src/__tests__/utils/fixtures.ts
src/components/CompareResults/SubtestsResults/SubtestsResultsTable.tsx
src/components/CompareResults/TableHeader.tsx
src/hooks/useTableSort.ts

This PR contains 2 simple commits:
1. For the "delta" column, this uses the absolute value instead of the signed value. Indeed it makes sense that when sorting descending (for example) the high negative values are also shown close to the top. This was an oversight from the initial implementation.
2. When clicking on the sorting button first, the direction is "descending" instead of "ascending", so that the highest values are shown at the top. I believe this is what the users are looking for usually, that's why it makes sense to get this with less clicks. Of course it's still possible to sort "ascending" with another click.
[deploy preview](https://deploy-preview-837--mozilla-perfcompare.netlify.app/subtests-compare-results?baseRev=d140333670bcd3103a668a5ec04ed438bb192368&baseRepo=mozilla-c …

Small adjustments on the sort functionality

---

src/__tests__/CompareResults/ResultsTable.test.tsx
src/components/CompareResults/ResultsTable.tsx
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsRevisionHeader.tsx
src/types/state.ts
src/utils/platform.ts

This mostly just changes the option in the menu, to be more consistent after @esanuandra 's changes in #816 :
This will also change the displayed platform from `OSX` to `macOS` when a platform isn't in the platform map.
I was also considering changing these to `macOS` as well for consistency: https://github.com/mozilla/perfcompare/blob/bee2cf6332a400ed477ebf2e415150d309cb1d96/src/utils/platform.ts#L23-L26
What do you think?
[deploy preview](http://localhost:3000/compare-results?baseRev=d140333670bcd3103a668a5ec04ed438bb192368&baseRepo=mozilla-central&newRev=250be4ca3c669db9a397456402f68249aa15d8d5&newRepo=mozilla-central&framework=1&sort=delta%7Cdesc&search=speedome)

Rename OSX to macOS to better reflect the newest naming for this platform

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsRevisionRow.test.tsx.snap
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/RevisionRowExpandable.tsx
src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx

[Bugzilla link](https://bugzilla.mozilla.org/show_bug.cgi?id=1935720)
[Bugzilla link 2](https://bugzilla.mozilla.org/show_bug.cgi?id=1935719)
[Deploy preview link](https://deploy-preview-826--mozilla-perfcompare.netlify.app/)
This PR improves the accessibility of the expand button for the revision row by adding proper ARIA attributes.
- Added `aria-expanded` to dynamically set to true or false based on the expanded state of the row.
- Added `aria-controls` that point to the `id` of the expandable section (`revision-row-expandable`)
- Changed the `div` being used for the expandable row to a `section`

Add aria expanded to revision row expand button

---

src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
src/components/CompareResults/SubtestsResults/SubtestsResultsTable.tsx

[Bugzilla number](https://bugzilla.mozilla.org/show_bug.cgi?id=1946314)
[Deploy link](https://deploy-preview-851--mozilla-perfcompare.netlify.app/subtests-compare-results?baseRev=731d4b2dcdc5955ba826a55077d5d5ba4b8e1ea8&baseRepo=mozilla-central&newRev=5041c20ccabb22016a82288a40bc13d845dfe2fe&newRepo=mozilla-central&framework=1&baseParentSignature=4769486&newParentSignature=4769486)
This PR adds a tooltip to the subtests view. Similar to what was done on this [PR](https://github.com/mozilla/perfcompare/pull/832)

Add tooltip to subtests page

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsRevisionRow.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
src/__tests__/TaskclusterAuth/__snapshots__/TaskclusterCallback.test.tsx.snap
src/__tests__/__snapshots__/App.test.tsx.snap
src/components/CompareResults/LinkToRevision.tsx
src/components/CompareResults/ResultsMain.tsx
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsRevisionHeader.tsx
src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx
src/components/CompareResults/TableHeader.tsx
src/components/CompareResults/TestHeader.tsx
src/styles/Fonts.ts
src/styles/SelectList.ts
src/styles/SelectedRevsStyle.ts
src/theme/components.js
src/theme/typography.ts

This PR updates the `lineHeight` to `1.5` everywhere, replacing pixel-based values in Fonts. Additionally, I have ensured the `h2` variant in `typography.ts` includes this update.

Increase `lineHeight` to `1.5`

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
src/components/CompareResults/TableHeader.tsx

[Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1946046)
[Deploy link](https://deploy-preview-854--mozilla-perfcompare.netlify.app/compare-results?baseRev=731d4b2dcdc5955ba826a55077d5d5ba4b8e1ea8&baseRepo=mozilla-central&newRev=5041c20ccabb22016a82288a40bc13d845dfe2fe&newRepo=mozilla-central&framework=1&filter_confidence=high)
This fixes the issue of tooltip overlapping the confidence filter menu when it's open.
I added a zindex to the filter menu so that it stacks higher than the tooltip. This would also work for other filters if we decide to add a tooltip to them later.
Update: When the filter menu is open, the tooltip still pops up. This happens because the tooltip is wrapping the whole `FiterableColumnHeader` component which includes the filter menu. I had to remove the …

add zindex to filter menu

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/Search/SelectedRevision.test.tsx
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
src/components/CompareResults/LinkToRevision.tsx
src/components/Search/SelectedRevisionItem.tsx
src/components/Shared/CopyIcon.tsx

[Bugzilla link](https://bugzilla.mozilla.org/show_bug.cgi?id=1938295)
[Deploy link](https://deploy-preview-841--mozilla-perfcompare.netlify.app/)
This PR adds a copy icon to easily copy revision hash
Changes:
- Created a `CopyIcon` component in `/components/Shared` folder
-  This component was used in `SelectedRevisionItem` and  `LinkToRevision` components to copy revision hash
Before
https://github.com/user-attachments/assets/cb73749e-b570-4a32-8006-69cc8c06b4bf
After 
https://github.com/user-attachments/assets/2ddd876e-1fb8-472c-a708-337b0b7dd1b2

Add a copy icon to easily copy revisions

---

src/__tests__/CompareResults/ResultsTable.test.tsx
src/__tests__/CompareResults/RevisionRow.test.tsx
src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/ResultsTable.tsx
src/components/CompareResults/TableContent.tsx
src/utils/platform.ts

[Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1943334)
[Deploy link](http://localhost:3000/compare-results?baseRev=0874fcba521fcf935ace34a3507f284de9bc4d79&baseRepo=autoland&newRev=e4734cd9848c0b570af98a9708da8fe4a2263b10&newRepo=autoland&framework=2&search=installer&filter_platform=windows)
This PR fixes incorrectly rendered platform names on the results table
Before
When macOS is filtered, we can still see windows as part of the result. [Live link](https://perf.compare/compare-results?baseRev=0874fcba521fcf935ace34a3507f284de9bc4d79&baseRepo=autoland&newRev=e4734cd9848c0b570af98a9708da8fe4a2263b10&newRepo=autoland&framework=2&search=installer&filter_platform=osx)
After
The platform name for Windows is `windows` so this wasn't capturing some windows platform with platform name …

Fix incorrectly rendered platform on results table

---

src/__tests__/CompareResults/RevisionRow.test.tsx
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/RunValues.tsx

This is a follow up PR for #844 
It adds the `Copy results` button inside the extended row.
[deploy test link](https://deploy-preview-859--mozilla-perfcompare.netlify.app/compare-over-time-results?baseRepo=try&selectedTimeRange=1209600&newRev=301fd7df21a146720ac180a15dbfd007b090dcaf&newRepo=try&framework=1)

Follow up PCF-561 Add copy run values to extended row

---

src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsRevisionRow.test.tsx.snap
src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx

[Bugzilla number](https://bugzilla.mozilla.org/show_bug.cgi?id=1943914)
[Deploy link](https://deploy-preview-863--mozilla-perfcompare.netlify.app/subtests-compare-results?baseRev=632d1b46eeba0e6950cb84fd950eceb086142d23&baseRepo=try&newRev=7c9e39d87387c3ed4c829ad5300ceb13705026e0&newRepo=try&framework=12&baseParentSignature=59287&newParentSignature=59287&sort=delta%7Cdesc&filter_status=improvement%2Cregression)
This PR fixes the alignment issue of long test names in the subtest revision row.
Before
After
Added `ellipse` and `overflow-hidden` to contain long test name
I also removed the `cell` styling from the test name column because `ellipse` wasn't working with `display:flex`

Fix alignment for long test name in subtest revision row

---

src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/Retrigger.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
src/__tests__/__snapshots__/App.test.tsx.snap
src/components/Search/SearchComponent.tsx
src/components/Search/SearchOverTime.tsx
src/components/Search/SelectedRevisionItem.tsx
src/styles/CompareCards.ts
src/styles/Fonts.ts
src/styles/SearchContainerStyles.ts
src/styles/SelectedRevsStyle.ts
src/theme/components.js

The latest deploy included some major font size UI bugs. This PR aims to fix these bugs.
Once this is approved, I'll go ahead and deploy to make sure production includes these changes. 
[Production Link](https://perf.compare/compare-results?baseRev=1e0be90a5631ba3c6f5f7f5e9b031bb0f635fe36&baseRepo=try&newRev=8ac2379c2250aff50be8b4c1c18b6344e92d399c&newRepo=try&framework=1)
*********************************
[Deploy Link](https://deploy-preview-873--mozilla-perfcompare.netlify.app/compare-results?baseRev=1e0be90a5631ba3c6f5f7f5e9b031bb0f635fe36&baseRepo=try&newRev=8ac2379c2250aff50be8b4c1c18b6344e92d399c&newRepo=try&framework=1)
Details:

Fix font UI bugs 

---

src/__tests__/CompareResults/ResultsTable.test.tsx
src/__tests__/CompareResults/RevisionRow.test.tsx
src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/ResultsTable.tsx
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsRevisionHeader.tsx
src/types/state.ts
src/utils/platform.ts

This is adding macOS 15, iOS as well as display the platforms in full when they're not recognized. Except for macOS 15, they are especially useful for the build_metrics framework.
[production](https://perf.compare/compare-results?baseRev=ba56f7ee55792aaf974891449b64ace32bc9e1b8&baseRepo=mozilla-central&newRev=30d833468eba8358571c55ec3e7e8991f4952fb9&newRepo=mozilla-central&framework=2) / [deploy preview](https://deploy-preview-881--mozilla-perfcompare.netlify.app/compare-results?baseRev=ba56f7ee55792aaf974891449b64ace32bc9e1b8&baseRepo=mozilla-central&newRev=30d833468eba8358571c55ec3e7e8991f4952fb9&newRepo=mozilla-central&framework=2)

Add missing platforms and show them when not found

---

src/__tests__/CompareResults/ResultsTable.test.tsx
src/components/CompareResults/TableHeader.tsx
src/hooks/useTableFilters.ts

Previously the internal state was keeping the _unchecked_ checkboxes, now it keeps the _checked_ checkboxes. This makes the code easier to follow.
The user-visible change is that unknown values are not filtered out as expected when the user selects specific filters. They are still visible when all filters are checked. This was the motivation to write this patch.
You can test with these links:
[main branch](https://main--mozilla-perfcompare.netlify.app/compare-results?baseRev=ba56f7ee55792aaf974891449b64ace32bc9e1b8&baseRepo=mozilla-central&newRev=30d833468eba8358571c55ec3e7e8991f4952fb9&newRepo=mozilla-central&framework=2&search=fetch_content) / [deploy preview](https://deploy-preview-882--mozilla-perfcompare.netlify.app/compare-results?baseRev=ba56f7ee55792aaf974891449b64ace32bc9e1b8&base …

Change how the filters are implemented so that the behavior is a bit better

---

src/__tests__/Search/fetchRevisionFromHash.test.tsx
src/components/App.tsx
src/components/CompareResults/ResultsView.tsx
src/components/CompareResults/hashToCommitLoader.ts
src/components/CompareResults/loader.ts
src/logic/treeherder.ts

What we are doing:
- 1) We are creating a new loader for perfcompare
- 2) Accomodating the updated tocommit api on treeherder to get back results faster
Why:
- 1) To leave the main loader alone and to create one specific to ./mach try perf
- 2) Treeherder needs extra information to get results faster, we are passing those results along to it

Bug 1962486 - Optimize and create new perfcompare loader

---

src/__tests__/Search/fetchRevisionFromLando.test.tsx
src/components/App.tsx
src/components/CompareResults/ResultsView.tsx
src/components/CompareResults/hashToCommitLoader.ts
src/components/CompareResults/landoToCommitLoader.ts
src/logic/lando.ts
src/logic/treeherder.ts
src/types/state.ts

In a previous PR I created a loader for perfcompare that used the ResultsView and created a page ./mach try perf could output a link to, and now that lando has ids for each push we can use that to make the links much shorter and more elegant.
Background to patch:
- In [my last PR](https://github.com/mozilla/perfcompare/pull/879) I created a compare-hash loader, it took 4 arguments(baseHash, newHash, baseHashDate, and newHashDate), the hashes were unique hashes of the time and author, attached within each pushes commit message, the dates were provided to narrow down the search range.
- This solution gave really long ugly urls and was complicated
Developments since the last patch:
- We now have lando ids being provided when we push to try and we can take the ids returned and get the …

Add ability to compare commits from ./mach try perf with lando ids

---

src/__tests__/CompareResults/Retrigger.test.tsx
src/components/CompareResults/DownloadButton.tsx
src/components/CompareResults/ResultsControls.tsx
src/components/CompareResults/Retrigger/RetriggerButton.tsx
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsMain.tsx

**Related PR: https://github.com/mozilla/perfcompare/pull/849**
This PR co-locates their respective disabled variants (`DisabledRetriggerButton` and `DisabledDownloadButton`) into the same files and also refactors the export style of `RetriggerButton` and `DownloadButton` by converting them to named exports to ensure consistency. These disabled buttons were previously defined inline in `SubtestsResultsMain` and have now been extracted for better separation of concerns.
- Converted `RetriggerButton` from default to named export to ensure consistency.
- Moved `DisabledRetriggerButton` from `SubtestsResultsMain` into the `RetriggerButton` file.
- Converted `DownloadButton` from default to named export to ensure consistency.
- Moved `DisabledDownloadButton` from `SubtestsResultsMain` into the …

Refactor: Move Disabled Variants of DownloadButton and RetriggerButton

---

src/components/CompareResults/Retrigger/RetriggerButton.tsx

While I was testing #907 I realized that we're doing a request to treeherder even when we don't have a job id to retrigger (this is when we don't have a run for the selected revision). That request was returning a 500 error. When testing locally, webpack was showing a full page error (fortunately that wasn't happening in production).
Ideally we should also be able to start a run by copying the other run's configuration (PCF-71), but that's some more work.
Also ideally the select input in the modal should be disabled with some information given to the user, but similarly this was more work than I was willing to do right now.
So the goal of this PR is simply to avoid sending requests when we don't have a job to retrigger, because this request was incorrect (had "undefined" as the job id in …

Do not do a request to taskcluster if there's no job to retrigger

---

src/__tests__/CompareResults/RevisionRow.test.tsx
src/__tests__/CompareResults/SubtestsRevisionRow.test.tsx
src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
src/components/CompareResults/ResultsMain.tsx
src/components/CompareResults/ResultsTable.tsx
src/components/CompareResults/RevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsMain.tsx
src/components/CompareResults/SubtestsResults/SubtestsResultsTable.tsx
src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx
src/components/CompareResults/SubtestsResults/SubtestsTableContent.tsx
src/components/CompareResults/TableContent.tsx
src/components/CompareResults/TableRevisionContent.tsx
src/components/CompareResults/hashToCommitLoader.ts
src/components/CompareResults/landoToCommitLoader.ts
src/components/CompareResults/loader.ts
src/components/CompareResults/overTimeLoader.ts
src/components/CompareResults/subtestsLoader.ts
src/components/CompareResults/subtestsOverTimeLoader.tsx
src/components/Shared/ToggleReplicatesButton.tsx
src/logic/treeherder.ts

Some exmples to look at:
Before: https://perf.compare/subtests-compare-results?baseRev=974421fd9d593416ba7308dbbaa7117096f68ad5&baseRepo=try&newRev=2c540969a27f657afc82f189d0c96280ac432d44&newRepo=try&framework=13&baseParentSignature=3444909&newParentSignature=3444909
After: https://deploy-preview-895--mozilla-perfcompare.netlify.app/subtests-compare-results?baseRev=974421fd9d593416ba7308dbbaa7117096f68ad5&baseRepo=try&newRev=2c540969a27f657afc82f189d0c96280ac432d44&newRepo=try&framework=13&baseParentSignature=3444909&newParentSignature=3444909&replicates=
Before: https://perf.compare/compare-lando-results?baseLando=140238&newLando=140239&baseRepo=try&newRepo=try&framework=13
After: https://deploy-preview-895--mozilla-perfcompare.netlify.app/compare-lando-results?baseLando=140238&newLando= …

Add a button to use replicates for comparisons when available

---

src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
src/components/CompareResults/RunValues.tsx

I'm a bit unsure about understanding the business logic correctly on the bug. Or what we would want as the string response for the standard deviation but I figure I'll just do the PR and get eyes on it quickly. 
[Deploy preview](https://deploy-preview-924--mozilla-perfcompare.netlify.app/compare-results?baseRev=7d880ff29269122bc521b3f69a643a3b7158a8eb&baseRepo=mozilla-central&newRev=31224efda311facc4ea54446610fd7c52d5d22a1&newRepo=try&framework=13&search=wikipedia)

#1931317 Show N/A string instead of 0 deviation
